cusinies_map = {
    'Taiwanese contemporary': 'Taiwanese',
    'Singaporean, Contemporary': 'Singaporean',
    'Cantonese': 'Cantonese',
    'Contemporary, Californian': 'Californian',
    'Contemporary, French': 'French',
    'Asian, Contemporary': 'Asian, Contemporary',
    'European Contemporary': 'European Contemporary',
    'French Contemporary': 'French Contemporary',
    'French': 'French',
    'Creative, Regional Cuisine': 'Creative, Regional Cuisine',
    'Modern Cuisine': 'Modern Cuisine',
    'Creative': 'Creative',
    'Creative, Contemporary': 'Creative, Contemporary',
    'Creative, Seafood': 'Creative, Seafood',
    'Modern Cuisine, Creative': 'Modern Cuisine, Creative',
    'Japanese': 'Japanese',
    'Innovative': 'Innovative',
    'Creative, Modern Cuisine': 'Creative, Modern Cuisine',
    'Classic French': 'Classic French',
    'Creative, International': 'Creative, International',
    'Modern French, Creative': 'Modern French, Creative',
    'Classic French, Creative': 'Classic French, Creative',
    'Seafood': 'Seafood',
    'Classic Cuisine': 'Classic Cuisine',
    'Mediterranean Cuisine, Modern Cuisine': 'Mediterranean Cuisine, Modern Cuisine',
    'Italian': 'Italian',
    'Sushi': 'Sushi',
    'Creative French': 'Creative French',
    'Creative British': 'Creative British',
    'Modern French': 'Modern French',
    'Modern British': 'Modern British',
    'French, French Contemporary': 'French, French Contemporary',
    'French, Contemporary': 'French, Contemporary',
    'Chinese': 'Chinese',
    'Creative, Innovative': 'Creative, Innovative',
    'Creative, Traditional Cuisine': 'Creative, Traditional Cuisine',
    'Italian Contemporary': 'Italian Contemporary',
    'Creative, Mediterranean Cuisine': 'Creative, Mediterranean Cuisine',
    'Mediterranean Cuisine, Contemporary': 'Mediterranean Cuisine, Contemporary',
    'Creative, Alpine': 'Creative, Alpine',
    'Creative, Seasonal Cuisine': 'Creative, Seasonal Cuisine',
    'American, French': 'American, French',
    'Vegan, Innovative': 'Vegan, Innovative',
    'Japanese, Sushi': 'Japanese, Sushi',
    'Contemporary, Creative': 'Contemporary, Creative',
    'Chao Zhou': 'Chao Zhou',
    'Taizhou': 'Taizhou',
    'Vegetarian': 'Vegetarian',
    'Creative, Farm to table': 'Creative, Farm to table',
    'Classic French, Seasonal Cuisine': 'Classic French, Seasonal Cuisine',
    'Creative, Country cooking': 'Creative, Country cooking',
    'Spanish Contemporary': 'Spanish Contemporary',
    'Asian Contemporary': 'Asian Contemporary',
    'Tempura': 'Tempura',
    'Contemporary': 'Contemporary',
    'Japanese, Seafood': 'Japanese, Seafood',
    'Contemporary, American': 'Contemporary, American',
    'Italian, Contemporary': 'Italian, Contemporary',
    'Contemporary, Modern Cuisine': 'Contemporary, Modern Cuisine',
    'Mexican, Contemporary': 'Mexican, Contemporary',
    'Californian, Contemporary': 'Californian, Contemporary',
    'Californian, Creative': 'Californian, Creative',
    'Indian': 'Indian',
    'Italian Contemporary, Modern Cuisine': 'Italian Contemporary, Modern Cuisine',
    'British Contemporary': 'British Contemporary',
    'Modern Cuisine, Swedish': 'Modern Cuisine, Swedish',
    'Modern French, Seasonal Cuisine': 'Modern French, Seasonal Cuisine',
    'Scandinavian': 'Scandinavian',
    'Modern Cuisine, Brazilian': 'Modern Cuisine, Brazilian',
    'Modern Cuisine, Innovative': 'Modern Cuisine, Innovative',
    'Mexican, Modern Cuisine': 'Mexican, Modern Cuisine',
    'Contemporary, Mexican': 'Contemporary, Mexican',
    'Tempura, Japanese': 'Tempura, Japanese',
    'Mediterranean Cuisine': 'Mediterranean Cuisine',
    'Modern Cuisine, Classic Cuisine': 'Modern Cuisine, Classic Cuisine',
    'Creative, Classic Cuisine': 'Creative, Classic Cuisine',
    'Modern Cuisine, Contemporary': 'Modern Cuisine, Contemporary',
    'Classic Cuisine, Modern Cuisine': 'Classic Cuisine, Modern Cuisine',
    'Creative French, International': 'Creative French, International',
    'Creative French, Classic Cuisine': 'Creative French, Classic Cuisine',
    'Asian, Creative': 'Asian, Creative',
    'Mediterranean Cuisine, Creative': 'Mediterranean Cuisine, Creative',
    'Modern Cuisine, Japanese Contemporary': 'Modern Cuisine, Japanese Contemporary',
    'French Contemporary, Classic Cuisine': 'French Contemporary, Classic Cuisine',
    'Modern Cuisine, Classic French': 'Modern Cuisine, Classic French',
    'Classic Cuisine, Creative': 'Classic Cuisine, Creative',
    'Innovative, Farm to table': 'Innovative, Farm to table',
    'Creative, Classic French': 'Creative, Classic French',
    'Classic French, Classic Cuisine': 'Classic French, Classic Cuisine',
    'Creative French, Modern Cuisine': 'Creative French, Modern Cuisine',
    'Creative, Modern French': 'Creative, Modern French',
    'Modern Cuisine, Mediterranean Cuisine': 'Modern Cuisine, Mediterranean Cuisine',
    'Japanese, Creative': 'Japanese, Creative',
    'Seafood, Modern Cuisine': 'Seafood, Modern Cuisine',
    'Seafood, Creative': 'Seafood, Creative',
    'Hunanese, Sichuan': 'Hunanese, Sichuan',
    'Huaiyang': 'Huaiyang',
    'Creative, Portuguese': 'Creative, Portuguese',
    'Modern French, Modern Cuisine': 'Modern French, Modern Cuisine',
    'Creative, Asian Influences': 'Creative, Asian Influences',
    'Traditional Cuisine': 'Traditional Cuisine',
    'Asian Influences, Creative': 'Asian Influences, Creative',
    'Classic French, Traditional Cuisine': 'Classic French, Traditional Cuisine',
    'Korean': 'Korean',
    'Korean, Korean Contemporary': 'Korean, Korean Contemporary',
    'Korean, Modern Cuisine': 'Korean, Modern Cuisine',
    'Contemporary, Seasonal Cuisine': 'Contemporary, Seasonal Cuisine',
    'Modern French, French Contemporary': 'Modern French, French Contemporary',
    'Turkish, Creative': 'Turkish, Creative',
    'Traditional British': 'Traditional British',
    'Thai contemporary': 'Thai contemporary',
    'German, Contemporary': 'German, Contemporary',
    'Southern Thai': 'Southern Thai',
    'Indian, Contemporary': 'Indian, Contemporary',
    'Thai': 'Thai',
    'Spanish, Contemporary': 'Spanish, Contemporary',
    'Creative, Italian and Japanese': 'Creative, Italian and Japanese',
    'Creative, Catalan': 'Creative, Catalan',
    'Creative, Castilian': 'Creative, Castilian',
    'Creative, Asturian': 'Creative, Asturian',
    'Malaysian, Creative': 'Malaysian, Creative',
    'Country cooking, Contemporary': 'Country cooking, Contemporary',
    'International, Contemporary': 'International, Contemporary',
    'Creative, Sicilian': 'Creative, Sicilian',
    'Italian Contemporary, Creative': 'Italian Contemporary, Creative',
    'Italian Contemporary, Mediterranean Cuisine': 'Italian Contemporary, Mediterranean Cuisine',
    'Country cooking, Modern Cuisine': 'Country cooking, Modern Cuisine',
    'Italian Contemporary, French': 'Italian Contemporary, French',
    'Creative, Campanian': 'Creative, Campanian',
    'Piedmontese, Modern Cuisine': 'Piedmontese, Modern Cuisine',
    'Creative, Italian Contemporary': 'Creative, Italian Contemporary',
    'Modern Cuisine, Turkish': 'Modern Cuisine, Turkish',
    'Japanese, Contemporary': 'Japanese, Contemporary',
    'Korean, Contemporary': 'Korean, Contemporary',
    'Contemporary, Alsatian': 'Contemporary, Alsatian',
    'Contemporary, French Contemporary': 'Contemporary, French Contemporary',
    'Scandinavian, Contemporary': 'Scandinavian, Contemporary',
    'Contemporary, American Contemporary': 'Contemporary, American Contemporary',
    'Creative, Greek': 'Creative, Greek',
    'Beijing Cuisine': 'Beijing Cuisine',
    'Shanghainese': 'Shanghainese',
    'Modern Cuisine, Seasonal Cuisine': 'Modern Cuisine, Seasonal Cuisine',
    'Sharing, Modern Cuisine': 'Sharing, Modern Cuisine',
    'Modern French, Contemporary': 'Modern French, Contemporary',
    'Farm to table, Creative': 'Farm to table, Creative',
    'Modern French, French': 'Modern French, French',
    'Mediterranean Cuisine, Seasonal Cuisine': 'Mediterranean Cuisine, Seasonal Cuisine',
    'Japanese Contemporary, Fusion': 'Japanese Contemporary, Fusion',
    'Modern French, Farm to table': 'Modern French, Farm to table',
    'Modern Cuisine, Hungarian': 'Modern Cuisine, Hungarian',
    'Creative, Hungarian': 'Creative, Hungarian',
    'Sichuan': 'Sichuan',
    'Organic, Vegan': 'Organic, Vegan',
    'Contemporary, Creative French': 'Contemporary, Creative French',
    'Latin American': 'Latin American',
    'Huaiyang, Sichuan': 'Huaiyang, Sichuan',
    'Taiwanese': 'Taiwanese',
    'Hang Zhou': 'Hang Zhou',
    'Barbecue': 'Barbecue',
    'Japanese Contemporary': 'Japanese Contemporary',
    'Steakhouse': 'Steakhouse',
    'Thai, Contemporary': 'Thai, Contemporary',
    'Steakhouse, American': 'Steakhouse, American',
    'Japanese, Traditional Cuisine': 'Japanese, Traditional Cuisine',
    'Californian, Farm to table': 'Californian, Farm to table',
    'Californian': 'Californian',
    'French, Californian': 'French, Californian',
    'Contemporary, Modern French': 'Contemporary, Modern French',
    'Contemporary, Seafood': 'Contemporary, Seafood',
    'American, Contemporary': 'American, Contemporary',
    'Contemporary, Italian': 'Contemporary, Italian',
    'Contemporary, Asian': 'Contemporary, Asian',
    'Chinese, Contemporary': 'Chinese, Contemporary',
    'Mexican, Seafood': 'Mexican, Seafood',
    'Californian, Italian': 'Californian, Italian',
    'Contemporary, Asian Contemporary': 'Contemporary, Asian Contemporary',
    'American, Classic Cuisine': 'American, Classic Cuisine',
    'Thai, Californian': 'Thai, Californian',
    'Seafood, Contemporary': 'Seafood, Contemporary',
    'Californian, Modern Cuisine': 'Californian, Modern Cuisine',
    'Portuguese': 'Portuguese',
    'Contemporary, Middle Eastern': 'Contemporary, Middle Eastern',
    'Indian Vegetarian': 'Indian Vegetarian',
    'Vietnamese Contemporary': 'Vietnamese Contemporary',
    'Teppanyaki': 'Teppanyaki',
    'Vietnamese': 'Vietnamese',
    'Contemporary, Croatian': 'Contemporary, Croatian',
    'Innovative, Singaporean': 'Innovative, Singaporean',
    'Malaysian, Contemporary': 'Malaysian, Contemporary',
    'Teochew': 'Teochew',
    'Korean Contemporary': 'Korean Contemporary',
    'Street Food': 'Street Food',
    'Peranakan': 'Peranakan',
    'Cantonese, Sichuan': 'Cantonese, Sichuan',
    'Modern Cuisine, Polish': 'Modern Cuisine, Polish',
    'Creative, Polish': 'Creative, Polish',
    'Spanish, Mediterranean Cuisine': 'Spanish, Mediterranean Cuisine',
    'Contemporary, Farm to table': 'Contemporary, Farm to table',
    'European': 'European',
    'Dim Sum': 'Dim Sum',
    'Fujian': 'Fujian',
    'Modern Cuisine, Regional Cuisine': 'Modern Cuisine, Regional Cuisine',
    'Grills': 'Grills',
    'Classic Cuisine, French': 'Classic Cuisine, French',
    'Modern Cuisine, French Contemporary': 'Modern Cuisine, French Contemporary',
    'Norwegian': 'Norwegian',
    'Modern Cuisine, Danish': 'Modern Cuisine, Danish',
    'Creative, Brazilian': 'Creative, Brazilian',
    'Asian Influences': 'Asian Influences',
    'Mexican': 'Mexican',
    'Creative, Vegetarian': 'Creative, Vegetarian',
    'Mexican, Traditional Cuisine': 'Mexican, Traditional Cuisine',
    'Mexican, Creative': 'Mexican, Creative',
    'Creative, Mexican': 'Creative, Mexican',
    'Mexican, Fusion': 'Mexican, Fusion',
    'Seafood, Mexican': 'Seafood, Mexican',
    'Zhejiang': 'Zhejiang',
    'Chinese Contemporary': 'Chinese Contemporary',
    'Peruvian, Contemporary': 'Peruvian, Contemporary',
    'Vietnamese, French': 'Vietnamese, French',
    'Colombian, Latin American': 'Colombian, Latin American',
    'Steakhouse, Spanish': 'Steakhouse, Spanish',
    'Korean, Steakhouse': 'Korean, Steakhouse',
    'Fusion, Sushi': 'Fusion, Sushi',
    'American': 'American',
    'Mexican, Regional Cuisine': 'Mexican, Regional Cuisine',
    'Fugu / Pufferfish': 'Fugu / Pufferfish',
    'Spanish': 'Spanish',
    'Yakitori': 'Yakitori',
    'Japanese, Tempura': 'Japanese, Tempura',
    'Italian, Italian Contemporary': 'Italian, Italian Contemporary',
    'Classic Cuisine, International': 'Classic Cuisine, International',
    'Classic French, Mediterranean Cuisine': 'Classic French, Mediterranean Cuisine',
    'Modern Cuisine, International': 'Modern Cuisine, International',
    'Modern Cuisine, Asian Influences': 'Modern Cuisine, Asian Influences',
    'Classic Cuisine, Seasonal Cuisine': 'Classic Cuisine, Seasonal Cuisine',
    'Classic Cuisine, Regional Cuisine': 'Classic Cuisine, Regional Cuisine',
    'Modern Cuisine, Modern French': 'Modern Cuisine, Modern French',
    'Creative, Japanese': 'Creative, Japanese',
    'French Contemporary, Creative': 'French Contemporary, Creative',
    'Seasonal Cuisine, Modern Cuisine': 'Seasonal Cuisine, Modern Cuisine',
    'Modern Cuisine, Farm to table': 'Modern Cuisine, Farm to table',
    'Modern French, Country cooking': 'Modern French, Country cooking',
    'Modern Cuisine, Country cooking': 'Modern Cuisine, Country cooking',
    'Mediterranean Cuisine, Greek': 'Mediterranean Cuisine, Greek',
    'Asian Influences, Classic French': 'Asian Influences, Classic French',
    'Asian Influences, Modern Cuisine': 'Asian Influences, Modern Cuisine',
    'Modern Cuisine, Russian': 'Modern Cuisine, Russian',
    'French Contemporary, Modern Cuisine': 'French Contemporary, Modern Cuisine',
    'Classic Cuisine, Traditional Cuisine': 'Classic Cuisine, Traditional Cuisine',
    'Classic French, Modern Cuisine': 'Classic French, Modern Cuisine',
    'Vegan, Creative': 'Vegan, Creative',
    'Farm to table, Country cooking': 'Farm to table, Country cooking',
    'Classic Cuisine, Mediterranean Cuisine': 'Classic Cuisine, Mediterranean Cuisine',
    'French, Seafood': 'French, Seafood',
    'Classic Cuisine, Modern French': 'Classic Cuisine, Modern French',
    'Classic Cuisine, Farm to table': 'Classic Cuisine, Farm to table',
    'Asian, Fusion': 'Asian, Fusion',
    'International, Modern Cuisine': 'International, Modern Cuisine',
    'Creative, North African': 'Creative, North African',
    'Farm to table, Classic French': 'Farm to table, Classic French',
    'Japanese, Japanese Contemporary': 'Japanese, Japanese Contemporary',
    'Farm to table, International': 'Farm to table, International',
    'Japanese, Modern Cuisine': 'Japanese, Modern Cuisine',
    'Fusion, Creative': 'Fusion, Creative',
    'Seasonal Cuisine, Regional Cuisine': 'Seasonal Cuisine, Regional Cuisine',
    'Classic French, Farm to table': 'Classic French, Farm to table',
    'Country cooking, Seasonal Cuisine': 'Country cooking, Seasonal Cuisine',
    'Austrian, French Contemporary': 'Austrian, French Contemporary',
    'Modern French, Mediterranean Cuisine': 'Modern French, Mediterranean Cuisine',
    'Seasonal Cuisine, Italian Contemporary': 'Seasonal Cuisine, Italian Contemporary',
    'International, Farm to table': 'International, Farm to table',
    'Israeli, Modern Cuisine': 'Israeli, Modern Cuisine',
    'Modern French, International': 'Modern French, International',
    'Mediterranean Cuisine, Farm to table': 'Mediterranean Cuisine, Farm to table',
    'Farm to table': 'Farm to table',
    'Regional Cuisine, Modern Cuisine': 'Regional Cuisine, Modern Cuisine',
    'Modern Cuisine, French': 'Modern Cuisine, French',
    'Fusion, Asian Influences': 'Fusion, Asian Influences',
    'French, International': 'French, International',
    'Innovative, International': 'Innovative, International',
    'Creative, Fusion': 'Creative, Fusion',
    'Classic French, Regional Cuisine': 'Classic French, Regional Cuisine',
    'Modern French, Classic Cuisine': 'Modern French, Classic Cuisine',
    'Farm to table, Modern Cuisine': 'Farm to table, Modern Cuisine',
    'Seasonal Cuisine, Classic Cuisine': 'Seasonal Cuisine, Classic Cuisine',
    'Italian, Mediterranean Cuisine': 'Italian, Mediterranean Cuisine',
    'Contemporary, Classic Cuisine': 'Contemporary, Classic Cuisine',
    'Classic Cuisine, Contemporary': 'Classic Cuisine, Contemporary',
    'Classic French, French': 'Classic French, French',
    'Farm to table, Classic Cuisine': 'Farm to table, Classic Cuisine',
    'Italian, Modern Cuisine': 'Italian, Modern Cuisine',
    'Farm to table, Mediterranean Cuisine': 'Farm to table, Mediterranean Cuisine',
    'Modern Cuisine, Seafood': 'Modern Cuisine, Seafood',
    'Seafood, Mediterranean Cuisine': 'Seafood, Mediterranean Cuisine',
    'Provençal': 'Provençal',
    'Thai, Asian Contemporary': 'Thai, Asian Contemporary',
    'Fusion': 'Fusion',
    'Peruvian': 'Peruvian',
    'Modern Cuisine, Japanese': 'Modern Cuisine, Japanese',
    'Greek, Mediterranean Cuisine': 'Greek, Mediterranean Cuisine',
    'Modern Cuisine, Traditional Cuisine': 'Modern Cuisine, Traditional Cuisine',
    'Traditional Cuisine, Classic Cuisine': 'Traditional Cuisine, Classic Cuisine',
    'Vegetarian, Mediterranean Cuisine': 'Vegetarian, Mediterranean Cuisine',
    'Provençal, Modern Cuisine': 'Provençal, Modern Cuisine',
    'Italian, Creative': 'Italian, Creative',
    'Noodles': 'Noodles',
    'Small eats': 'Small eats',
    'Dumplings': 'Dumplings',
    'Indonesian': 'Indonesian',
    'Hunanese, Jiangzhe': 'Hunanese, Jiangzhe',
    'Congee': 'Congee',
    'Jiangzhe': 'Jiangzhe',
    'Asian': 'Asian',
    'Hakkanese': 'Hakkanese',
    'Pizza': 'Pizza',
    'Filipino, Contemporary': 'Filipino, Contemporary',
    'International, Fusion': 'International, Fusion',
    'Chinese, Shanghainese': 'Chinese, Shanghainese',
    'Italian, Milanese': 'Italian, Milanese',
    'Mexican, Tex-Mex': 'Mexican, Tex-Mex',
    'Chinese, Dumplings': 'Chinese, Dumplings',
    'Japanese, Izakaya': 'Japanese, Izakaya',
    'Southern, Creole': 'Southern, Creole',
    'Japanese, Ramen': 'Japanese, Ramen',
    'Italian, Pizza': 'Italian, Pizza',
    'Californian, American': 'Californian, American',
    'International': 'International',
    'Italian, Regional Cuisine': 'Italian, Regional Cuisine',
    'Chinese, Dim Sum': 'Chinese, Dim Sum',
    'Indonesian, Thai and Vietnamese': 'Indonesian, Thai and Vietnamese',
    'Pizza, Italian-American': 'Pizza, Italian-American',
    'Gastropub': 'Gastropub',
    'Seafood, Italian-American': 'Seafood, Italian-American',
    'Deli, American': 'Deli, American',
    'Italian-American': 'Italian-American',
    'Chinese, Sichuan': 'Chinese, Sichuan',
    'Middle Eastern': 'Middle Eastern',
    'Chinese, Regional Cuisine': 'Chinese, Regional Cuisine',
    'Italian-American, American': 'Italian-American, American',
    'Pizza, Italian': 'Pizza, Italian',
    'Chinese, Cantonese': 'Chinese, Cantonese',
    'Californian, Pizza': 'Californian, Pizza',
    'Mediterranean Cuisine, Middle Eastern': 'Mediterranean Cuisine, Middle Eastern',
    'Asian, Taiwanese': 'Asian, Taiwanese',
    'Barbecue, Regional Cuisine': 'Barbecue, Regional Cuisine',
    'Italian, Californian': 'Italian, Californian',
    'Seafood, Californian': 'Seafood, Californian',
    'Korean, Duck Specialities': 'Korean, Duck Specialities',
    'Vietnamese, Noodles': 'Vietnamese, Noodles',
    'Mexican, Californian': 'Mexican, Californian',
    'Chinese, Taiwanese': 'Chinese, Taiwanese',
    'Vegan': 'Vegan',
    'Burmese': 'Burmese',
    'Pizza, Californian': 'Pizza, Californian',
    'Fusion, Chinese': 'Fusion, Chinese',
    'Contemporary, Vietnamese': 'Contemporary, Vietnamese',
    'Malaysian': 'Malaysian',
    'Pakistani, Indian': 'Pakistani, Indian',
    'Ethiopian': 'Ethiopian',
    'Portuguese, Regional Cuisine': 'Portuguese, Regional Cuisine',
    'South East Asian, Californian': 'South East Asian, Californian',
    'Fusion, Indian': 'Fusion, Indian',
    'Lebanese': 'Lebanese',
    'Asian and Western': 'Asian and Western',
    'Persian': 'Persian',
    'Balkan': 'Balkan',
    'Emirati Cuisine': 'Emirati Cuisine',
    'Regional Cuisine, Meats and Grills': 'Regional Cuisine, Meats and Grills',
    'Regional Cuisine': 'Regional Cuisine',
    'Farm to table, Contemporary': 'Farm to table, Contemporary',
    'Balkan, Meats and Grills': 'Balkan, Meats and Grills',
    'Country cooking, Regional Cuisine': 'Country cooking, Regional Cuisine',
    'Country cooking': 'Country cooking',
    'Singaporean': 'Singaporean',
    'Meats and Grills, Polish': 'Meats and Grills, Polish',
    'Mediterranean Cuisine, Polish': 'Mediterranean Cuisine, Polish',
    'Traditional Cuisine, Polish': 'Traditional Cuisine, Polish',
    'South American': 'South American',
    'Modern Cuisine, Regional European': 'Modern Cuisine, Regional European',
    'Regional Cuisine, Country cooking': 'Regional Cuisine, Country cooking',
    'Regional Cuisine, Seasonal Cuisine': 'Regional Cuisine, Seasonal Cuisine',
    'Meats and Grills': 'Meats and Grills',
    'Regional European, Farm to table': 'Regional European, Farm to table',
    'Italian, Traditional Cuisine': 'Italian, Traditional Cuisine',
    'Xibei': 'Xibei',
    'Noodles and Congee': 'Noodles and Congee',
    'Hunanese': 'Hunanese',
    'Swedish': 'Swedish',
    'Scandinavian, Swedish': 'Scandinavian, Swedish',
    'Norwegian, Contemporary': 'Norwegian, Contemporary',
    'Smørrebrød, Seasonal Cuisine': 'Smørrebrød, Seasonal Cuisine',
    'Norwegian, Modern Cuisine': 'Norwegian, Modern Cuisine',
    'Smørrebrød': 'Smørrebrød',
    'Danish': 'Danish',
    'Brazilian': 'Brazilian',
    'Brazilian, Farm to table': 'Brazilian, Farm to table',
    'French, Regional Cuisine': 'French, Regional Cuisine',
    'Meats and Grills, International': 'Meats and Grills, International',
    'Seasonal Cuisine, Farm to table': 'Seasonal Cuisine, Farm to table',
    'Fusion, Modern Cuisine': 'Fusion, Modern Cuisine',
    'Mexican, Mediterranean Cuisine': 'Mexican, Mediterranean Cuisine',
    'Grills, International': 'Grills, International',
    'Fusion, Mexican': 'Fusion, Mexican',
    'Unagi / Freshwater Eel': 'Unagi / Freshwater Eel',
    'Soba': 'Soba',
    'Kushiage': 'Kushiage',
    'Ramen': 'Ramen',
    'Ningbo': 'Ningbo',
    'Cuban, Regional Cuisine': 'Cuban, Regional Cuisine',
    'Cuban': 'Cuban',
    'Cuban, American': 'Cuban, American',
    'Nepali, Indian': 'Nepali, Indian',
    'Japanese, Udon': 'Japanese, Udon',
    'Contemporary, Bakery': 'Contemporary, Bakery',
    'American, Southern': 'American, Southern',
    'Greek': 'Greek',
    'Mediterranean Cuisine, Turkish': 'Mediterranean Cuisine, Turkish',
    'Bakery, American': 'Bakery, American',
    'Ramen, Japanese': 'Ramen, Japanese',
    'Izakaya': 'Izakaya',
    'Tonkatsu': 'Tonkatsu',
    'Udon': 'Udon',
    'Oden': 'Oden',
    'Yoshoku': 'Yoshoku',
    'Shojin': 'Shojin',
    'Teppanyaki, Okonomiyaki': 'Teppanyaki, Okonomiyaki',
    'Obanzai': 'Obanzai',
    'World Cuisine': 'World Cuisine',
    'Country cooking, Mediterranean Cuisine': 'Country cooking, Mediterranean Cuisine',
    'Country cooking, Farm to table': 'Country cooking, Farm to table',
    'Country cooking, International': 'Country cooking, International',
    'Country cooking, Classic Cuisine': 'Country cooking, Classic Cuisine',
    'Country cooking, French Contemporary': 'Country cooking, French Contemporary',
    'Country cooking, Traditional Cuisine': 'Country cooking, Traditional Cuisine',
    'Italian, Seasonal Cuisine': 'Italian, Seasonal Cuisine',
    'International, Regional Cuisine': 'International, Regional Cuisine',
    'Traditional Cuisine, Country cooking': 'Traditional Cuisine, Country cooking',
    'International, Traditional Cuisine': 'International, Traditional Cuisine',
    'Austrian, Traditional Cuisine': 'Austrian, Traditional Cuisine',
    'Classic Cuisine, Home Cooking': 'Classic Cuisine, Home Cooking',
    'Contemporary, International': 'Contemporary, International',
    'Traditional Cuisine, Seasonal Cuisine': 'Traditional Cuisine, Seasonal Cuisine',
    'Farm to table, Seasonal Cuisine': 'Farm to table, Seasonal Cuisine',
    'Regional Cuisine, Farm to table': 'Regional Cuisine, Farm to table',
    'Contemporary, Country cooking': 'Contemporary, Country cooking',
    'Farm to table, Bavarian': 'Farm to table, Bavarian',
    'Country cooking, Home Cooking': 'Country cooking, Home Cooking',
    'Farm to table, German': 'Farm to table, German',
    'Seasonal Cuisine': 'Seasonal Cuisine',
    'Austrian, Country cooking': 'Austrian, Country cooking',
    'Farm to table, Regional Cuisine': 'Farm to table, Regional Cuisine',
    'Organic, Country cooking': 'Organic, Country cooking',
    'Portuguese, Mediterranean Cuisine': 'Portuguese, Mediterranean Cuisine',
    'Seasonal Cuisine, International': 'Seasonal Cuisine, International',
    'Regional Cuisine, International': 'Regional Cuisine, International',
    'Mediterranean Cuisine, International': 'Mediterranean Cuisine, International',
    'International, Seafood': 'International, Seafood',
    'Traditional Cuisine, International': 'Traditional Cuisine, International',
    'Mediterranean Cuisine, Country cooking': 'Mediterranean Cuisine, Country cooking',
    'International, Meats and Grills': 'International, Meats and Grills',
    'Alpine, Regional Cuisine': 'Alpine, Regional Cuisine',
    'German, Seasonal Cuisine': 'German, Seasonal Cuisine',
    'Regional Cuisine, Creative': 'Regional Cuisine, Creative',
    'Contemporary, Fusion': 'Contemporary, Fusion',
    'International, Country cooking': 'International, Country cooking',
    'Izakaya, Sharing': 'Izakaya, Sharing',
    'Regional Cuisine, Contemporary': 'Regional Cuisine, Contemporary',
    'Asian and Western, International': 'Asian and Western, International',
    'Home Cooking, Country cooking': 'Home Cooking, Country cooking',
    'Seasonal Cuisine, Traditional Cuisine': 'Seasonal Cuisine, Traditional Cuisine',
    'Traditional Cuisine, Provençal': 'Traditional Cuisine, Provençal',
    'Traditional Cuisine, Modern Cuisine': 'Traditional Cuisine, Modern Cuisine',
    'Savoyard': 'Savoyard',
    'Modern Cuisine, Alsatian': 'Modern Cuisine, Alsatian',
    'Corsican': 'Corsican',
    'Modern Cuisine, Catalan': 'Modern Cuisine, Catalan',
    'Seafood, Traditional Cuisine': 'Seafood, Traditional Cuisine',
    'Alsatian, Traditional Cuisine': 'Alsatian, Traditional Cuisine',
    'Alsatian': 'Alsatian',
    'Alsatian, Country cooking': 'Alsatian, Country cooking',
    'Catalan': 'Catalan',
    'Breton': 'Breton',
    'Traditional Cuisine, Alsatian': 'Traditional Cuisine, Alsatian',
    'Modern Cuisine, Gastropub': 'Modern Cuisine, Gastropub',
    'Mediterranean Cuisine, Traditional Cuisine': 'Mediterranean Cuisine, Traditional Cuisine',
    'Cantonese Roast Meats': 'Cantonese Roast Meats',
    'Chiu Chow': 'Chiu Chow',
    'Macanese': 'Macanese',
    'Shanghainese, Sichuan': 'Shanghainese, Sichuan',
    'Singaporean and Malaysian': 'Singaporean and Malaysian',
    'Xinjiang': 'Xinjiang',
    'Shun Tak': 'Shun Tak',
    'Portuguese, Contemporary': 'Portuguese, Contemporary',
    'Modern French, Cuisine from the Marches': 'Modern French, Cuisine from the Marches',
    'Belgian': 'Belgian',
    'Seasonal Cuisine, Country cooking': 'Seasonal Cuisine, Country cooking',
    'Sharing, Country cooking': 'Sharing, Country cooking',
    'Traditional Cuisine, Farm to table': 'Traditional Cuisine, Farm to table',
    'Modern Cuisine, Italian': 'Modern Cuisine, Italian',
    'Seasonal Cuisine, World Cuisine': 'Seasonal Cuisine, World Cuisine',
    'Mediterranean Cuisine, Sharing': 'Mediterranean Cuisine, Sharing',
    'Traditional Cuisine, Classic French': 'Traditional Cuisine, Classic French',
    'Regional Cuisine, Classic Cuisine': 'Regional Cuisine, Classic Cuisine',
    'Home Cooking': 'Home Cooking',
    'Cuisine from South West France, Country cooking': 'Cuisine from South West France, Country cooking',
    'Classic Cuisine, French Contemporary': 'Classic Cuisine, French Contemporary',
    'Thai, Asian': 'Thai, Asian',
    'Lebanese, Middle Eastern': 'Lebanese, Middle Eastern',
    'Traditional Cuisine, Sharing': 'Traditional Cuisine, Sharing',
    'Meats and Grills, Classic French': 'Meats and Grills, Classic French',
    'Sharing': 'Sharing',
    'Grills, Traditional Cuisine': 'Grills, Traditional Cuisine',
    'Meats and Grills, Classic Cuisine': 'Meats and Grills, Classic Cuisine',
    'Farm to table, Creative French': 'Farm to table, Creative French',
    'Modern French, Traditional Cuisine': 'Modern French, Traditional Cuisine',
    'Creative French, Fusion': 'Creative French, Fusion',
    'Home Cooking, Grills': 'Home Cooking, Grills',
    'Traditional Cuisine, French': 'Traditional Cuisine, French',
    'Mediterranean Cuisine, Modern French': 'Mediterranean Cuisine, Modern French',
    'Organic, Vegetarian': 'Organic, Vegetarian',
    'Traditional Cuisine, Modern French': 'Traditional Cuisine, Modern French',
    'Classic French, Country cooking': 'Classic French, Country cooking',
    'French Contemporary, Creative French': 'French Contemporary, Creative French',
    'Italian, Organic': 'Italian, Organic',
    'Sharing, International': 'Sharing, International',
    'Dwaeji-gukbap': 'Dwaeji-gukbap',
    'Gomtang': 'Gomtang',
    'Naengmyeon': 'Naengmyeon',
    'Chueotang': 'Chueotang',
    'Gejang': 'Gejang',
    'Yukhoe': 'Yukhoe',
    'Bulgogi': 'Bulgogi',
    'Memil-guksu': 'Memil-guksu',
    'Mandu': 'Mandu',
    'Seolleongtang': 'Seolleongtang',
    'Dubu': 'Dubu',
    'Jokbal': 'Jokbal',
    'Doganitang': 'Doganitang',
    'Kalguksu': 'Kalguksu',
    'Sujebi': 'Sujebi',
    'Dwaeji-gukbap, Korean': 'Dwaeji-gukbap, Korean',
    'Unagi / Freshwater Eel, Japanese': 'Unagi / Freshwater Eel, Japanese',
    'Asian, Singaporean': 'Asian, Singaporean',
    'Asian, South American': 'Asian, South American',
    'South Indian, Sri Lankan': 'South Indian, Sri Lankan',
    'Vegetarian, Modern Cuisine': 'Vegetarian, Modern Cuisine',
    'Mediterranean Cuisine, Asian Influences': 'Mediterranean Cuisine, Asian Influences',
    'Traditional British, Mediterranean Cuisine': 'Traditional British, Mediterranean Cuisine',
    'Contemporary, Scottish': 'Contemporary, Scottish',
    'North African, Mediterranean Cuisine': 'North African, Mediterranean Cuisine',
    'Meats and Grills, Barbecue': 'Meats and Grills, Barbecue',
    'Middle Eastern, Mediterranean Cuisine': 'Middle Eastern, Mediterranean Cuisine',
    'Thai, South East Asian': 'Thai, South East Asian',
    'Creole, Cajun': 'Creole, Cajun',
    'Modern Cuisine, European': 'Modern Cuisine, European',
    'Scottish, Traditional Cuisine': 'Scottish, Traditional Cuisine',
    'South African': 'South African',
    'Sri Lankan, Contemporary': 'Sri Lankan, Contemporary',
    'Isan': 'Isan',
    'Thai-Chinese': 'Thai-Chinese',
    'Northern Thai': 'Northern Thai',
    'Thai-Chinese, Southern Thai': 'Thai-Chinese, Southern Thai',
    'Congee, Thai-Chinese': 'Congee, Thai-Chinese',
    'Lebanese, Armenian': 'Lebanese, Armenian',
    'Onigiri': 'Onigiri',
    'Pork': 'Pork',
    'Sri Lankan': 'Sri Lankan',
    'Pork, Regional Cuisine': 'Pork, Regional Cuisine',
    'Galician, Contemporary': 'Galician, Contemporary',
    'Rice Dishes': 'Rice Dishes',
    'Traditional Cuisine, Regional Cuisine': 'Traditional Cuisine, Regional Cuisine',
    'Traditional Cuisine, Creative': 'Traditional Cuisine, Creative',
    'Farm to table, Traditional Cuisine': 'Farm to table, Traditional Cuisine',
    'Regional Cuisine, Traditional Cuisine': 'Regional Cuisine, Traditional Cuisine',
    'Contemporary, Andalusian': 'Contemporary, Andalusian',
    'Contemporary, Regional Cuisine': 'Contemporary, Regional Cuisine',
    'Traditional Cuisine, Contemporary': 'Traditional Cuisine, Contemporary',
    'Contemporary, Traditional Cuisine': 'Contemporary, Traditional Cuisine',
    'Galician': 'Galician',
    'Seafood, Regional Cuisine': 'Seafood, Regional Cuisine',
    'Modern Cuisine, Fusion': 'Modern Cuisine, Fusion',
    'Contemporary, Rice Dishes': 'Contemporary, Rice Dishes',
    'Catalan, Traditional Cuisine': 'Catalan, Traditional Cuisine',
    'International, Mediterranean Cuisine': 'International, Mediterranean Cuisine',
    'Rice Dishes, Traditional Cuisine': 'Rice Dishes, Traditional Cuisine',
    'Regional Cuisine, Mediterranean Cuisine': 'Regional Cuisine, Mediterranean Cuisine',
    'Basque': 'Basque',
    'Traditional Cuisine, Meats and Grills': 'Traditional Cuisine, Meats and Grills',
    'Rice Dishes, Farm to table': 'Rice Dishes, Farm to table',
    'Seafood, Farm to table': 'Seafood, Farm to table',
    'Modern Cuisine, Rice Dishes': 'Modern Cuisine, Rice Dishes',
    'Andalusian': 'Andalusian',
    'Argentinian': 'Argentinian',
    'Grills, Argentinian': 'Grills, Argentinian',
    'Traditional Cuisine, Home Cooking': 'Traditional Cuisine, Home Cooking',
    'Malaysian, Peranakan': 'Malaysian, Peranakan',
    'Malaysian, Indonesian': 'Malaysian, Indonesian',
    'Noodles, Shanghainese': 'Noodles, Shanghainese',
    'Tuscan, Traditional Cuisine': 'Tuscan, Traditional Cuisine',
    'Venetian, Traditional Cuisine': 'Venetian, Traditional Cuisine',
    'Venetian, Seasonal Cuisine': 'Venetian, Seasonal Cuisine',
    'Emilian, Traditional Cuisine': 'Emilian, Traditional Cuisine',
    'Piedmontese, Traditional Cuisine': 'Piedmontese, Traditional Cuisine',
    'Cuisine from Valtellina, Traditional Cuisine': 'Cuisine from Valtellina, Traditional Cuisine',
    'Sicilian, Traditional Cuisine': 'Sicilian, Traditional Cuisine',
    'Cuisine from Abruzzo': 'Cuisine from Abruzzo',
    'Sardinian, Traditional Cuisine': 'Sardinian, Traditional Cuisine',
    'Cuisine from the Marches, Modern Cuisine': 'Cuisine from the Marches, Modern Cuisine',
    'Lombardian, Country cooking': 'Lombardian, Country cooking',
    'Apulian, Seafood': 'Apulian, Seafood',
    'Tuscan': 'Tuscan',
    'Mantuan, Seasonal Cuisine': 'Mantuan, Seasonal Cuisine',
    'Roman, Cuisine from Lazio': 'Roman, Cuisine from Lazio',
    'Cuisine from Abruzzo, Traditional Cuisine': 'Cuisine from Abruzzo, Traditional Cuisine',
    'Cuisine from Basilicata, Traditional Cuisine': 'Cuisine from Basilicata, Traditional Cuisine',
    'Umbrian, Traditional Cuisine': 'Umbrian, Traditional Cuisine',
    'Venetian, Modern Cuisine': 'Venetian, Modern Cuisine',
    'Apulian': 'Apulian',
    'Ligurian': 'Ligurian',
    'Apulian, Modern Cuisine': 'Apulian, Modern Cuisine',
    'Ligurian, Traditional Cuisine': 'Ligurian, Traditional Cuisine',
    'Piedmontese': 'Piedmontese',
    'Cuisine from Basilicata': 'Cuisine from Basilicata',
    'South Tyrolean, Seasonal Cuisine': 'South Tyrolean, Seasonal Cuisine',
    'Piedmontese, Classic Cuisine': 'Piedmontese, Classic Cuisine',
    'Ligurian, Seasonal Cuisine': 'Ligurian, Seasonal Cuisine',
    'Indian, Asian': 'Indian, Asian',
    'Lombardian, Traditional Cuisine': 'Lombardian, Traditional Cuisine',
    'Emilian, Seasonal Cuisine': 'Emilian, Seasonal Cuisine',
    'Creative, Emilian': 'Creative, Emilian',
    'Emilian, Country cooking': 'Emilian, Country cooking',
    'Seafood, Classic Cuisine': 'Seafood, Classic Cuisine',
    'Cuisine from Lazio, Traditional Cuisine': 'Cuisine from Lazio, Traditional Cuisine',
    'Campanian, Traditional Cuisine': 'Campanian, Traditional Cuisine',
    'Cuisine from Abruzzo, Contemporary': 'Cuisine from Abruzzo, Contemporary',
    'Contemporary, Vegetarian': 'Contemporary, Vegetarian',
    'Venetian, Classic Cuisine': 'Venetian, Classic Cuisine',
    'Sicilian': 'Sicilian',
    'Cuisine from Abruzzo, Meats and Grills': 'Cuisine from Abruzzo, Meats and Grills',
    'Friulian, Seasonal Cuisine': 'Friulian, Seasonal Cuisine',
    'Emilian, Meats and Grills': 'Emilian, Meats and Grills',
    'Regional Cuisine, Alpine': 'Regional Cuisine, Alpine',
    'Seafood, Campanian': 'Seafood, Campanian',
    'Country cooking, Organic': 'Country cooking, Organic',
    'Campanian, Modern Cuisine': 'Campanian, Modern Cuisine',
    'Cuisine from Abruzzo, Seafood': 'Cuisine from Abruzzo, Seafood',
    'Cuisine from the Marches, Traditional Cuisine': 'Cuisine from the Marches, Traditional Cuisine',
    'Seasonal Cuisine, Contemporary': 'Seasonal Cuisine, Contemporary',
    'Cuisine from the Marches, Meats and Grills': 'Cuisine from the Marches, Meats and Grills',
    'Cuisine from Romagna': 'Cuisine from Romagna',
    'Chinese, Asian Contemporary': 'Chinese, Asian Contemporary',
    'Seafood, Seasonal Cuisine': 'Seafood, Seasonal Cuisine',
    'Apulian, Traditional Cuisine': 'Apulian, Traditional Cuisine',
    'Emilian': 'Emilian',
    'Cuisine from Romagna, Traditional Cuisine': 'Cuisine from Romagna, Traditional Cuisine',
    'Friulian, Traditional Cuisine': 'Friulian, Traditional Cuisine',
    'Country cooking, Campanian': 'Country cooking, Campanian',
    'Seafood, Ligurian': 'Seafood, Ligurian',
    'Campanian, Home Cooking': 'Campanian, Home Cooking',
    'Calabrian, Traditional Cuisine': 'Calabrian, Traditional Cuisine',
    'Seafood, Venetian': 'Seafood, Venetian',
    'Campanian, Country cooking': 'Campanian, Country cooking',
    'Cuisine from Lazio, Seafood': 'Cuisine from Lazio, Seafood',
    'Emilian, Modern Cuisine': 'Emilian, Modern Cuisine',
    'Sicilian, Country cooking': 'Sicilian, Country cooking',
    'Tuscan, Meats and Grills': 'Tuscan, Meats and Grills',
    'Cuisine from Valtellina': 'Cuisine from Valtellina',
    'Cuisine from the Aosta Valley, Italian': 'Cuisine from the Aosta Valley, Italian',
    'Sicilian, Seafood': 'Sicilian, Seafood',
    'Lombardian, Contemporary': 'Lombardian, Contemporary',
    'Lombardian': 'Lombardian',
    'Cuisine from Lazio, Seasonal Cuisine': 'Cuisine from Lazio, Seasonal Cuisine',
    'Sardinian, Mediterranean Cuisine': 'Sardinian, Mediterranean Cuisine',
    'Lombardian, Seasonal Cuisine': 'Lombardian, Seasonal Cuisine',
    'Piedmontese, Country cooking': 'Piedmontese, Country cooking',
    'Emilian, Home Cooking': 'Emilian, Home Cooking',
    'Roman, Traditional Cuisine': 'Roman, Traditional Cuisine',
    'Campanian, Mediterranean Cuisine': 'Campanian, Mediterranean Cuisine',
    'Chinese, Modern Cuisine': 'Chinese, Modern Cuisine',
    'Umbrian': 'Umbrian',
    'Innovative, Lombardian': 'Innovative, Lombardian',
    'Seafood, Cuisine from the Marches': 'Seafood, Cuisine from the Marches',
    'Sardinian, Creative': 'Sardinian, Creative',
    'Italian Contemporary, Italian': 'Italian Contemporary, Italian',
    'Tuscan, Country cooking': 'Tuscan, Country cooking',
    'Apulian, Country cooking': 'Apulian, Country cooking',
    'Classic Cuisine, Italian Contemporary': 'Classic Cuisine, Italian Contemporary',
    'Country cooking, Grills': 'Country cooking, Grills',
    'Emilian, Classic Cuisine': 'Emilian, Classic Cuisine',
    'Sicilian, Modern Cuisine': 'Sicilian, Modern Cuisine',
    'Mantuan, Lombardian': 'Mantuan, Lombardian',
    'Turkish, Traditional Cuisine': 'Turkish, Traditional Cuisine',
    'Turkish, Contemporary': 'Turkish, Contemporary',
    'Organic, Seasonal Cuisine': 'Organic, Seasonal Cuisine',
    'Turkish': 'Turkish',
    'Turkish, Modern Cuisine': 'Turkish, Modern Cuisine',
    'Grills, Turkish': 'Grills, Turkish',
    'Caribbean, Regional Cuisine': 'Caribbean, Regional Cuisine',
    'Creole, Creative': 'Creole, Creative',
    'Indian, Regional Cuisine': 'Indian, Regional Cuisine',
    'South East Asian, Lao': 'South East Asian, Lao',
    'Asian, Sichuan': 'Asian, Sichuan',
    'American, Chicken Specialities': 'American, Chicken Specialities',
    'Southern, Regional Cuisine': 'Southern, Regional Cuisine',
    'Seafood, Barbecue': 'Seafood, Barbecue',
    'Asian, South East Asian': 'Asian, South East Asian',
    'Peruvian, South American': 'Peruvian, South American',
    'Afghan': 'Afghan',
    'Italian, Campanian': 'Italian, Campanian',
    'Korean, Fusion': 'Korean, Fusion',
    'Italian-American, Italian': 'Italian-American, Italian',
    'Seafood, Spanish': 'Seafood, Spanish',
    'Tibetan': 'Tibetan',
    'Vegetarian, Contemporary': 'Vegetarian, Contemporary',
    'Middle Eastern, Israeli': 'Middle Eastern, Israeli',
    'Deli': 'Deli',
    'Vegan, Italian-American': 'Vegan, Italian-American',
    'Italian, Roman': 'Italian, Roman',
    'Thai, Fusion': 'Thai, Fusion',
    'Vietnamese, Modern Cuisine': 'Vietnamese, Modern Cuisine',
    'Asian, Chicken Specialities': 'Asian, Chicken Specialities',
    'Italian, Italian-American': 'Italian, Italian-American',
    'Southern, American': 'Southern, American',
    'Tex-Mex': 'Tex-Mex',
    'American, Deli': 'American, Deli',
    'Middle Eastern, Vegetarian': 'Middle Eastern, Vegetarian',
    'American, American Contemporary': 'American, American Contemporary',
    'Peruvian, Fusion': 'Peruvian, Fusion',
    'Filipino, Asian': 'Filipino, Asian',
    'French, Country cooking': 'French, Country cooking',
    'Italian, Sicilian': 'Italian, Sicilian',
    'Central Asian, Regional Cuisine': 'Central Asian, Regional Cuisine',
    'Japanese, Soba': 'Japanese, Soba',
    'Croatian, Seafood': 'Croatian, Seafood',
    'Czech': 'Czech',
    'Italian, Gastropub': 'Italian, Gastropub',
    'Thai, Isan': 'Thai, Isan',
    'Polish, Dumplings': 'Polish, Dumplings',
    'Korean, Barbecue': 'Korean, Barbecue',
    'Central Asian': 'Central Asian',
    'Korean, Vegetarian': 'Korean, Vegetarian',
    'American, Italian': 'American, Italian',
    'Fusion, Asian': 'Fusion, Asian',
    'Italian-American, Pizza': 'Italian-American, Pizza',
    'Spanish, Spanish Contemporary': 'Spanish, Spanish Contemporary',
    'International, Asian': 'International, Asian',
    'Fusion, Contemporary': 'Fusion, Contemporary',
    'Chinese, American': 'Chinese, American',
    'Vegan, American': 'Vegan, American',
    'Korean, American': 'Korean, American',
    'Mediterranean Cuisine, American Contemporary': 'Mediterranean Cuisine, American Contemporary',
    'Filipino': 'Filipino',
    'Deli, Italian': 'Deli, Italian',
    'American, Gastropub': 'American, Gastropub',
    'Italian, American': 'Italian, American',
    'Contemporary, Mediterranean Cuisine': 'Contemporary, Mediterranean Cuisine',
    'Gastropub, English': 'Gastropub, English',
    'Peruvian, Latin American': 'Peruvian, Latin American',
    'Indian, Fusion': 'Indian, Fusion',
    'Austrian': 'Austrian',
    'Gastropub, American Contemporary': 'Gastropub, American Contemporary',
    'Spanish, Basque': 'Spanish, Basque',
    'Southern': 'Southern',
    'Small eats, Venezuelan': 'Small eats, Venezuelan',
    'Mediterranean Cuisine, Fusion': 'Mediterranean Cuisine, Fusion',
    'Hotpot': 'Hotpot',
    'Shandong': 'Shandong',
    'Hubei': 'Hubei',
    'Contemporary, Southern': 'Contemporary, Southern',
    'Vietnamese, Cambodian': 'Vietnamese, Cambodian',
    'Vietnamese, Regional Cuisine': 'Vietnamese, Regional Cuisine',
    'Thai, Regional Cuisine': 'Thai, Regional Cuisine',
    'Udon, Japanese': 'Udon, Japanese',
    'Contemporary, North American': 'Contemporary, North American',
    'Swiss, Regional Cuisine': 'Swiss, Regional Cuisine',
    'Swiss, Country cooking': 'Swiss, Country cooking',
    'Swiss, Traditional Cuisine': 'Swiss, Traditional Cuisine',
    'International, Swiss': 'International, Swiss',
    'Sicilian, Classic Cuisine': 'Sicilian, Classic Cuisine',
    'Traditional Cuisine, Swiss': 'Traditional Cuisine, Swiss',
    'French Contemporary, Farm to table': 'French Contemporary, Farm to table',
    'Creative, World Cuisine': 'Creative, World Cuisine',
    'Vegan, Modern Cuisine': 'Vegan, Modern Cuisine',
    'Swiss': 'Swiss',
    'Austrian, Seasonal Cuisine': 'Austrian, Seasonal Cuisine',
    'French, Traditional Cuisine': 'French, Traditional Cuisine',
    'Country cooking, Swiss': 'Country cooking, Swiss',
    'Asian, Sushi': 'Asian, Sushi',
    'Farm to table, Grills': 'Farm to table, Grills',
    'French, Farm to table': 'French, Farm to table',
    'Turkish, Mediterranean Cuisine': 'Turkish, Mediterranean Cuisine',
    'Italian, Classic Cuisine': 'Italian, Classic Cuisine',
    'Farm to table, Piedmontese': 'Farm to table, Piedmontese',
    'French, Seasonal Cuisine': 'French, Seasonal Cuisine',
    'International, Seasonal Cuisine': 'International, Seasonal Cuisine',
    'Swiss, Farm to table': 'Swiss, Farm to table',
    'Farm to table, Modern French': 'Farm to table, Modern French',
    'Scandinavian, Farm to table': 'Scandinavian, Farm to table',
    'Creative, Bakery': 'Creative, Bakery',
    'Mexican, Vegan': 'Mexican, Vegan',
    'Hungarian': 'Hungarian',
    'Contemporary, Hungarian': 'Contemporary, Hungarian',
    'Barbecue, American': 'Barbecue, American',
    'Chinese, Asian': 'Chinese, Asian',
    'Israeli, Mediterranean Cuisine': 'Israeli, Mediterranean Cuisine',
    'Yunnanese': 'Yunnanese',
    'Mediterranean Cuisine, Spanish': 'Mediterranean Cuisine, Spanish',
    'Mediterranean Cuisine, Italian': 'Mediterranean Cuisine, Italian',
    'Asian, Asian Contemporary': 'Asian, Asian Contemporary',
    'Creative French, Modern French': 'Creative French, Modern French',
    'Asian Contemporary, Sharing': 'Asian Contemporary, Sharing',
    'Country cooking, Cuisine from the Marches': 'Country cooking, Cuisine from the Marches',
    'Asian, Chinese': 'Asian, Chinese',
    'Modern Cuisine, Asian Contemporary': 'Modern Cuisine, Asian Contemporary',
    'French Contemporary, International': 'French Contemporary, International',
    'Organic, Farm to table': 'Organic, Farm to table',
    'Mediterranean Cuisine, Italian-American': 'Mediterranean Cuisine, Italian-American',
    'Modern Cuisine, Sharing': 'Modern Cuisine, Sharing',
    'Modern Cuisine, Scandinavian': 'Modern Cuisine, Scandinavian',
    'International, Asian Influences': 'International, Asian Influences',
    'Portuguese, Classic Cuisine': 'Portuguese, Classic Cuisine',
    'Cantonese, Chinese Contemporary': 'Cantonese, Chinese Contemporary',
    'Farm to table, Meats and Grills': 'Farm to table, Meats and Grills',
    'Vegan, Chinese': 'Vegan, Chinese',
    'South East Asian': 'South East Asian',
    'Shabu-shabu': 'Shabu-shabu',
    'Sichuan, Taiwanese': 'Sichuan, Taiwanese',
    'Modern Cuisine, Apulian': 'Modern Cuisine, Apulian',
    'Modern Cuisine, Tuscan': 'Modern Cuisine, Tuscan',
    'Seasonal Cuisine, Tuscan': 'Seasonal Cuisine, Tuscan',
    'Sukiyaki': 'Sukiyaki',
    'Italian, Tuscan': 'Italian, Tuscan',
    'Chinese, Duck Specialities': 'Chinese, Duck Specialities',
    'Chinese, Hunanese and Sichuan': 'Chinese, Hunanese and Sichuan',
    'Sushi, Contemporary': 'Sushi, Contemporary',
    'Latin American, American Contemporary': 'Latin American, American Contemporary',
    'Californian, Mediterranean Cuisine': 'Californian, Mediterranean Cuisine',
    'Farm to table, Italian': 'Farm to table, Italian',
    'Steakhouse, Regional Cuisine': 'Steakhouse, Regional Cuisine',
    'Middle Eastern, Californian': 'Middle Eastern, Californian',
    'Californian, American Contemporary': 'Californian, American Contemporary',
    'Seafood, Shellfish Specialities': 'Seafood, Shellfish Specialities',
    'Thai, Lao': 'Thai, Lao',
    'Steakhouse, American Contemporary': 'Steakhouse, American Contemporary',
    'Armenian': 'Armenian',
    'Portuguese, Californian': 'Portuguese, Californian',
    'Puerto Rican': 'Puerto Rican',
    'Mediterranean Cuisine, Californian': 'Mediterranean Cuisine, Californian',
    'Italian, Steakhouse': 'Italian, Steakhouse',
    'Indian, Gastropub': 'Indian, Gastropub',
    'Malaysian, Californian': 'Malaysian, Californian',
    'American, International': 'American, International',
    'Vietnamese, Contemporary': 'Vietnamese, Contemporary',
    'Moroccan, Mexican': 'Moroccan, Mexican',
    'Izakaya, Sushi': 'Izakaya, Sushi',
    'Seafood, American': 'Seafood, American',
    'Noodles, Asian': 'Noodles, Asian',
    'Chinese, Beijing Cuisine': 'Chinese, Beijing Cuisine',
    'Californian, Vegetarian': 'Californian, Vegetarian',
    'American, Steakhouse': 'American, Steakhouse',
    'Californian, Seafood': 'Californian, Seafood',
    'Austrian, European Contemporary': 'Austrian, European Contemporary',
    'Greek, Seafood': 'Greek, Seafood',
    'Mediterranean Cuisine, American': 'Mediterranean Cuisine, American',
    'Korean, Regional Cuisine': 'Korean, Regional Cuisine',
    'European, Californian': 'European, Californian',
    'American, Seafood': 'American, Seafood',
    'Japanese, Californian': 'Japanese, Californian',
    'Indian, Californian': 'Indian, Californian',
    'Korean, Beef': 'Korean, Beef',
    'Ethiopian, American': 'Ethiopian, American',
    'Contemporary, Japanese': 'Contemporary, Japanese',
    'Mexican, Latin American': 'Mexican, Latin American',
    'Californian, Seasonal Cuisine': 'Californian, Seasonal Cuisine',
    'Filipino, Californian': 'Filipino, Californian',
    'Filipino, Fusion': 'Filipino, Fusion',
    'Colombian, Contemporary': 'Colombian, Contemporary',
    'Italian, Seafood': 'Italian, Seafood',
    'Asian, American': 'Asian, American',
    'Japanese, Sukiyaki': 'Japanese, Sukiyaki',
    'Moroccan, Middle Eastern': 'Moroccan, Middle Eastern',
    'Indian, Classic Cuisine': 'Indian, Classic Cuisine',
    'Sushi, Japanese': 'Sushi, Japanese',
    'Greek, Californian': 'Greek, Californian',
    'Moroccan, Contemporary': 'Moroccan, Contemporary',
    'Vegan, Asian': 'Vegan, Asian',
    'Thai, American': 'Thai, American',
    'Californian, French': 'Californian, French',
    'International, American Contemporary': 'International, American Contemporary',
    'American, Californian': 'American, Californian',
    'Steakhouse, Contemporary': 'Steakhouse, Contemporary',
    'Japanese, Curry': 'Japanese, Curry',
    'French, American': 'French, American',
    'Pizza, Contemporary': 'Pizza, Contemporary',
    'Persian, Grills': 'Persian, Grills',
    'Steakhouse, Californian': 'Steakhouse, Californian',
    'Mexican, Persian': 'Mexican, Persian',
    'Japanese, Peruvian': 'Japanese, Peruvian',
    'Japanese Contemporary, Korean': 'Japanese Contemporary, Korean',
    'Contemporary, Galician': 'Contemporary, Galician',
    'Mediterranean Cuisine, French': 'Mediterranean Cuisine, French',
    'Meats and Seafood': 'Meats and Seafood',
    'French, Classic Cuisine': 'French, Classic Cuisine',
    'Seafood, Asian': 'Seafood, Asian',
    'Italian, International': 'Italian, International',
    'Campanian': 'Campanian',
    'Italian Contemporary, Regional Cuisine': 'Italian Contemporary, Regional Cuisine',
    'Modern Cuisine, Italian Contemporary': 'Modern Cuisine, Italian Contemporary',
    'Croatian': 'Croatian',
    'Mediterranean Cuisine, Meats and Grills': 'Mediterranean Cuisine, Meats and Grills',
    'Japanese, Fusion': 'Japanese, Fusion',
    'Classic Cuisine, Seafood': 'Classic Cuisine, Seafood',
    'Japanese, International': 'Japanese, International',
    'Mediterranean Cuisine, Croatian': 'Mediterranean Cuisine, Croatian',
    'Asian Influences, Asian and Western': 'Asian Influences, Asian and Western',
    'Mediterranean Cuisine, Seafood': 'Mediterranean Cuisine, Seafood',
    'Modern Cuisine, Meats and Grills': 'Modern Cuisine, Meats and Grills',
    'Japanese, Asian': 'Japanese, Asian',
    'Seasonal Cuisine, Mediterranean Cuisine': 'Seasonal Cuisine, Mediterranean Cuisine',
    'Traditional Cuisine, Mediterranean Cuisine': 'Traditional Cuisine, Mediterranean Cuisine',
    'Croatian, Contemporary': 'Croatian, Contemporary',
    'Mediterranean Cuisine, Classic Cuisine': 'Mediterranean Cuisine, Classic Cuisine',
    'Asturian, Contemporary': 'Asturian, Contemporary',
    'Lyonnaise, French': 'Lyonnaise, French',
    'Barbecue, Grills': 'Barbecue, Grills',
    'Organic': 'Organic',
    'Modern French, Asian Influences': 'Modern French, Asian Influences',
    'French, Modern Cuisine': 'French, Modern Cuisine',
    'Teochew, Cantonese': 'Teochew, Cantonese',
    'Californian, Asian Contemporary': 'Californian, Asian Contemporary',
    'Japanese, Korean': 'Japanese, Korean',
    'Seasonal Cuisine, French': 'Seasonal Cuisine, French',
    'Meats and Grills, Seafood': 'Meats and Grills, Seafood',
    'Meats and Grills, Traditional Cuisine': 'Meats and Grills, Traditional Cuisine',
    'Innovative, Polish': 'Innovative, Polish',
    'Traditional Cuisine, Organic': 'Traditional Cuisine, Organic',
    'Mediterranean Cuisine, Grills': 'Mediterranean Cuisine, Grills',
    'Regional Cuisine, Pizza': 'Regional Cuisine, Pizza',
    'European, Mediterranean Cuisine': 'European, Mediterranean Cuisine',
    'Farm to table, Regional European': 'Farm to table, Regional European',
    'Regional Cuisine, Innovative': 'Regional Cuisine, Innovative',
    'Regional Cuisine, Grills': 'Regional Cuisine, Grills',
    'International, Creative': 'International, Creative',
    'American Contemporary': 'American Contemporary',
    'Caribbean, African': 'Caribbean, African',
    'Contemporary, Italian Contemporary': 'Contemporary, Italian Contemporary',
    'Traditional Cuisine, Italian': 'Traditional Cuisine, Italian',
    'Creative, Italian': 'Creative, Italian',
    'Seasonal Cuisine, Alpine': 'Seasonal Cuisine, Alpine',
    'Hainanese': 'Hainanese',
    'Fusion, Mediterranean Cuisine': 'Fusion, Mediterranean Cuisine',
    'German': 'German',
    'Modern Cuisine, Organic': 'Modern Cuisine, Organic',
    'Modern Cuisine, Finnish': 'Modern Cuisine, Finnish',
    'Vegetarian, Creative': 'Vegetarian, Creative',
    'Smørrebrød, Danish': 'Smørrebrød, Danish',
    'Modern Cuisine, Asian': 'Modern Cuisine, Asian',
    'Danish, Country cooking': 'Danish, Country cooking',
    'Finnish': 'Finnish',
    'Danish, Seasonal Cuisine': 'Danish, Seasonal Cuisine',
    'Spanish, Norwegian': 'Spanish, Norwegian',
    'Italian and Japanese': 'Italian and Japanese',
    'Contemporary, European Contemporary': 'Contemporary, European Contemporary',
    'Vegan, Vegetarian': 'Vegan, Vegetarian',
    'Swedish, Modern Cuisine': 'Swedish, Modern Cuisine',
    'Regional Cuisine, Swedish': 'Regional Cuisine, Swedish',
    'Brazilian, Contemporary': 'Brazilian, Contemporary',
    'Brazilian, Modern Cuisine': 'Brazilian, Modern Cuisine',
    'Brazilian, Grills': 'Brazilian, Grills',
    'Farm to table, Home Cooking': 'Farm to table, Home Cooking',
    'Italian, Brazilian': 'Italian, Brazilian',
    'Peruvian, Farm to table': 'Peruvian, Farm to table',
    'Spanish, Rice Dishes': 'Spanish, Rice Dishes',
    'European, Italian': 'European, Italian',
    'French Contemporary, South American': 'French Contemporary, South American',
    'Japanese, Farm to table': 'Japanese, Farm to table',
    'Brazilian, Pork': 'Brazilian, Pork',
    'Asian Contemporary, Dim Sum': 'Asian Contemporary, Dim Sum',
    'Tuscan, Home Cooking': 'Tuscan, Home Cooking',
    'Seafood, International': 'Seafood, International',
    'Chicken Specialities': 'Chicken Specialities',
    'Regional Cuisine, Mexican': 'Regional Cuisine, Mexican',
    'Traditional Cuisine, Mexican': 'Traditional Cuisine, Mexican',
    'Mexican, Bakery': 'Mexican, Bakery',
    'International, Mexican': 'International, Mexican',
    'Mexican, International': 'Mexican, International',
    'Moroccan': 'Moroccan',
    'Mexican, Vegetarian': 'Mexican, Vegetarian',
    'Beef': 'Beef',
    'Eastern European': 'Eastern European',
    'Tonkatsu, Yoshoku': 'Tonkatsu, Yoshoku',
    'Italian, American Contemporary': 'Italian, American Contemporary',
    'American, Regional Cuisine': 'American, Regional Cuisine',
    'Cuban, Spanish': 'Cuban, Spanish',
    'American, Fusion': 'American, Fusion',
    'Contemporary, Steakhouse': 'Contemporary, Steakhouse',
    'Peruvian, Seafood': 'Peruvian, Seafood',
    'Asian, Mediterranean Cuisine': 'Asian, Mediterranean Cuisine',
    'Argentinian, Steakhouse': 'Argentinian, Steakhouse',
    'European, Contemporary': 'European, Contemporary',
    'Cuban, Latin American': 'Cuban, Latin American',
    'Southern, Steakhouse': 'Southern, Steakhouse',
    'Lao': 'Lao',
    'American, Bakery': 'American, Bakery',
    'Fusion, Vietnamese': 'Fusion, Vietnamese',
    'Asian, Japanese': 'Asian, Japanese',
    'Contemporary, Deli': 'Contemporary, Deli',
    'Vegan, Farm to table': 'Vegan, Farm to table',
    'Italian, Modern French': 'Italian, Modern French',
    'French, Asian': 'French, Asian',
    'Puerto Rican, Regional Cuisine': 'Puerto Rican, Regional Cuisine',
    'Duck Specialities': 'Duck Specialities', nan: nan, 'South American, Fusion': 'South American, Fusion',
    'Regional European': 'Regional European',
    'Contemporary, Meats and Grills': 'Contemporary, Meats and Grills',
    'Mantuan, Modern Cuisine': 'Mantuan, Modern Cuisine',
    'Sardinian': 'Sardinian',
    'Grills, Farm to table': 'Grills, Farm to table',
    'Contemporary, Sharing': 'Contemporary, Sharing',
    'Vegetarian, French': 'Vegetarian, French',
    'Cantonese, Chinese': 'Cantonese, Chinese',
    'Country cooking, Asian': 'Country cooking, Asian',
    'Austrian, International': 'Austrian, International',
    'German, Modern Cuisine': 'German, Modern Cuisine',
    'Austrian, Modern Cuisine': 'Austrian, Modern Cuisine',
    'Bavarian, International': 'Bavarian, International',
    'Classic French, International': 'Classic French, International',
    'Seafood, Vegetarian': 'Seafood, Vegetarian',
    'Country cooking, German': 'Country cooking, German',
    'International, Classic Cuisine': 'International, Classic Cuisine',
    'Italian, Farm to table': 'Italian, Farm to table',
    'Classic French, French Contemporary': 'Classic French, French Contemporary',
    'Meats and Grills, American': 'Meats and Grills, American',
    'African': 'African',
    'International, French': 'International, French',
    'Innovative, Regional Cuisine': 'Innovative, Regional Cuisine',
    'Mediterranean Cuisine, Regional Cuisine': 'Mediterranean Cuisine, Regional Cuisine',
    'Chinese, French': 'Chinese, French',
    'Classic French, Meats and Grills': 'Classic French, Meats and Grills',
    'Seafood, Meats and Grills': 'Seafood, Meats and Grills',
    'Korean, Spanish': 'Korean, Spanish',
    'Modern Cuisine, German': 'Modern Cuisine, German',
    'Asian Influences, Contemporary': 'Asian Influences, Contemporary',
    'Spanish Contemporary, Modern Cuisine': 'Spanish Contemporary, Modern Cuisine',
    'Japanese Contemporary, South American': 'Japanese Contemporary, South American',
    'Regional Cuisine, Spanish': 'Regional Cuisine, Spanish',
    'Alpine, Modern Cuisine': 'Alpine, Modern Cuisine',
    'Bavarian, Traditional Cuisine': 'Bavarian, Traditional Cuisine',
    'Vegan, Japanese': 'Vegan, Japanese',
    'Farm to table, French Contemporary': 'Farm to table, French Contemporary',
    'Modern French, Fusion': 'Modern French, Fusion',
    'Japanese Contemporary, Creative': 'Japanese Contemporary, Creative',
    'Classic Cuisine, Country cooking': 'Classic Cuisine, Country cooking',
    'Country cooking, French': 'Country cooking, French',
    'Country cooking, Regional European': 'Country cooking, Regional European',
    'Asian Influences, Regional Cuisine': 'Asian Influences, Regional Cuisine',
    'Regional European, Country cooking': 'Regional European, Country cooking',
    'French, German': 'French, German',
    'Peruvian, International': 'Peruvian, International',
    'Grills, Mediterranean Cuisine': 'Grills, Mediterranean Cuisine',
    'South East Asian, Vietnamese': 'South East Asian, Vietnamese',
    'French, Mediterranean Cuisine': 'French, Mediterranean Cuisine',
    'French, European Contemporary': 'French, European Contemporary',
    'Swabian, Farm to table': 'Swabian, Farm to table',
    'French Contemporary, Regional Cuisine': 'French Contemporary, Regional Cuisine',
    'Grills, Meats and Grills': 'Grills, Meats and Grills',
    'Japanese Contemporary, Peruvian': 'Japanese Contemporary, Peruvian',
    'Seasonal Cuisine, Creative': 'Seasonal Cuisine, Creative',
    'French Contemporary, German': 'French Contemporary, German',
    'Contemporary, Regional European': 'Contemporary, Regional European',
    'French, Creative': 'French, Creative',
    'Israeli, Contemporary': 'Israeli, Contemporary',
    'French Contemporary, Modern French': 'French Contemporary, Modern French',
    'Modern Cuisine, European Contemporary': 'Modern Cuisine, European Contemporary',
    'Regional Cuisine, Seafood': 'Regional Cuisine, Seafood',
    'Japanese Contemporary, European': 'Japanese Contemporary, European',
    'Vegetarian, Farm to table': 'Vegetarian, Farm to table',
    'Home Cooking, International': 'Home Cooking, International',
    'Bavarian, Seasonal Cuisine': 'Bavarian, Seasonal Cuisine',
    'Farm to table, French': 'Farm to table, French',
    'Meats and Grills, Seasonal Cuisine': 'Meats and Grills, Seasonal Cuisine',
    'Modern Cuisine, Provençal': 'Modern Cuisine, Provençal',
    'Traditional Cuisine, Lyonnaise': 'Traditional Cuisine, Lyonnaise',
    'Barbecue, Argentinian': 'Barbecue, Argentinian',
    'Italian, Provençal': 'Italian, Provençal',
    'Traditional Cuisine, Cuisine from Franche-Comté': 'Traditional Cuisine, Cuisine from Franche-Comté',
    'Traditional Cuisine, Grills': 'Traditional Cuisine, Grills',
    'Provençal, Mediterranean Cuisine': 'Provençal, Mediterranean Cuisine',
    'Burgundian': 'Burgundian',
    'Cheese, Fondue and Raclette': 'Cheese, Fondue and Raclette',
    'Yakitori, Japanese': 'Yakitori, Japanese',
    'Lyonnaise': 'Lyonnaise',
    'Provençal, Classic Cuisine': 'Provençal, Classic Cuisine',
    'Cuisine from South West France': 'Cuisine from South West France',
    'Israeli': 'Israeli',
    'Corsican, Country cooking': 'Corsican, Country cooking',
    'Lyonnaise, Traditional Cuisine': 'Lyonnaise, Traditional Cuisine',
    'Modern Cuisine, Grills': 'Modern Cuisine, Grills',
    'Farm to table, Cuisine from South West France': 'Farm to table, Cuisine from South West France',
    'Thai, Japanese': 'Thai, Japanese',
    'Basque, Traditional Cuisine': 'Basque, Traditional Cuisine',
    'Modern Cuisine, Filipino': 'Modern Cuisine, Filipino',
    'Provençal, Contemporary': 'Provençal, Contemporary',
    'Israeli, Middle Eastern': 'Israeli, Middle Eastern',
    'Seafood, Grills': 'Seafood, Grills',
    'Meats and Grills, Argentinian': 'Meats and Grills, Argentinian',
    'Mediterranean Cuisine, Israeli': 'Mediterranean Cuisine, Israeli',
    'Teppanyaki, Japanese': 'Teppanyaki, Japanese',
    'Innovative, Contemporary': 'Innovative, Contemporary',
    'Traditional Cuisine, Portuguese': 'Traditional Cuisine, Portuguese',
    'Regional European, Contemporary': 'Regional European, Contemporary',
    'Vegetarian, Vegan': 'Vegetarian, Vegan',
    'Creative, Grills': 'Creative, Grills',
    'Australian Contemporary': 'Australian Contemporary',
    'Portuguese, Creative': 'Portuguese, Creative',
    'French, Asian Influences': 'French, Asian Influences',
    'Chinese, Fusion': 'Chinese, Fusion',
    'Belgian, French': 'Belgian, French',
    'Flemish, Regional Cuisine': 'Flemish, Regional Cuisine',
    'French Contemporary, Asian Influences': 'French Contemporary, Asian Influences',
    'Organic, Modern Cuisine': 'Organic, Modern Cuisine',
    'Classic Cuisine, Classic French': 'Classic Cuisine, Classic French',
    'French, Creative French': 'French, Creative French',
    'Sharing, Contemporary': 'Sharing, Contemporary',
    'Classic French, Italian Contemporary': 'Classic French, Italian Contemporary',
    'French Contemporary, Seasonal Cuisine': 'French Contemporary, Seasonal Cuisine',
    'Mediterranean Cuisine, Sardinian': 'Mediterranean Cuisine, Sardinian',
    'Vegetarian, Seafood': 'Vegetarian, Seafood',
    'Contemporary, Barbecue': 'Contemporary, Barbecue',
    'Fusion, Italian Contemporary': 'Fusion, Italian Contemporary',
    'Farm to table, Vegetarian': 'Farm to table, Vegetarian',
    'Meats and Grills, Country cooking': 'Meats and Grills, Country cooking',
    'Modern Cuisine, Creative French': 'Modern Cuisine, Creative French',
    'Classic Cuisine, Creative French': 'Classic Cuisine, Creative French',
    'Creative, Organic': 'Creative, Organic',
    'Creative, Creative French': 'Creative, Creative French',
    'Modern French, Creative French': 'Modern French, Creative French',
    'Meats and Grills, Grills': 'Meats and Grills, Grills',
    'Classic Cuisine, Belgian': 'Classic Cuisine, Belgian',
    'French, Belgian': 'French, Belgian',
    'Seafood, Classic French': 'Seafood, Classic French',
    'Traditional Cuisine, Seafood': 'Traditional Cuisine, Seafood',
    'Beef, Farm to table': 'Beef, Farm to table',
    'Belgian, Classic Cuisine': 'Belgian, Classic Cuisine',
    'Modern French, World Cuisine': 'Modern French, World Cuisine',
    'French Contemporary, Mediterranean Cuisine': 'French Contemporary, Mediterranean Cuisine',
    'Meats and Grills, Modern French': 'Meats and Grills, Modern French',
    'Vegetarian, Organic': 'Vegetarian, Organic',
    'Belgian, Classic French': 'Belgian, Classic French',
    'Creative French, Belgian': 'Creative French, Belgian',
    'Roman': 'Roman',
    'Creative French, Traditional Cuisine': 'Creative French, Traditional Cuisine',
    'Traditional Cuisine, Belgian': 'Traditional Cuisine, Belgian',
    'Flemish': 'Flemish',
    'Grills, Classic Cuisine': 'Grills, Classic Cuisine',
    'Organic, Modern French': 'Organic, Modern French',
    'Korean, Asian': 'Korean, Asian',
    'Chinese, Organic': 'Chinese, Organic',
    'Classic Cuisine, Italian': 'Classic Cuisine, Italian',
    'Modern French, Seafood': 'Modern French, Seafood',
    'Seasonal Cuisine, Belgian': 'Seasonal Cuisine, Belgian',
    'Belgian, Traditional Cuisine': 'Belgian, Traditional Cuisine',
    'World Cuisine, Farm to table': 'World Cuisine, Farm to table',
    'French, Modern French': 'French, Modern French',
    'Contemporary, Japanese Contemporary': 'Contemporary, Japanese Contemporary',
    'Korean, Classic Cuisine': 'Korean, Classic Cuisine',
    'Contemporary, Scandinavian': 'Contemporary, Scandinavian',
    'Noodles, Taiwanese': 'Noodles, Taiwanese',
    'French, Classic French': 'French, Classic French',
    'Italian Contemporary, Tuscan': 'Italian Contemporary, Tuscan',
    'Piedmontese, Seafood': 'Piedmontese, Seafood',
    'Piedmontese, Seasonal Cuisine': 'Piedmontese, Seasonal Cuisine',
    'Regional Cuisine, Traditional British': 'Regional Cuisine, Traditional British',
    'Vegetarian, Asian Influences': 'Vegetarian, Asian Influences',
    'Seafood, Scottish': 'Seafood, Scottish',
    'Traditional British, Regional Cuisine': 'Traditional British, Regional Cuisine',
    'Basque, Spanish': 'Basque, Spanish',
    'Modern British, Grills': 'Modern British, Grills',
    'Modern British, Modern Cuisine': 'Modern British, Modern Cuisine',
    'Irish': 'Irish',
    'Italian, Japanese Contemporary': 'Italian, Japanese Contemporary',
    'Barbecue, Creative': 'Barbecue, Creative',
    'Latin American, European Contemporary': 'Latin American, European Contemporary',
    'Seafood, Oyster Specialities': 'Seafood, Oyster Specialities',
    'Italian, Modern British': 'Italian, Modern British',
    'Modern Cuisine, Scottish': 'Modern Cuisine, Scottish',
    'Meats and Grills, Traditional British': 'Meats and Grills, Traditional British',
    'Mediterranean Cuisine, Traditional British': 'Mediterranean Cuisine, Traditional British',
    'European Contemporary, European': 'European Contemporary, European',
    'Mediterranean Cuisine, Rice Dishes': 'Mediterranean Cuisine, Rice Dishes',
    'Irish, Modern Cuisine': 'Irish, Modern Cuisine',
    'South American, Mediterranean Cuisine': 'South American, Mediterranean Cuisine',
    'Polish': 'Polish',
    'Classic Cuisine, Irish': 'Classic Cuisine, Irish',
    'Modern British, Seafood': 'Modern British, Seafood',
    'Modern Cuisine, Middle Eastern': 'Modern Cuisine, Middle Eastern',
    'Modern British, Creative': 'Modern British, Creative',
    'Swedish, Asian Influences': 'Swedish, Asian Influences',
    'Contemporary, Piedmontese': 'Contemporary, Piedmontese',
    'Contemporary, Emilian': 'Contemporary, Emilian',
    'Modern Cuisine, Balkan': 'Modern Cuisine, Balkan',
    'International, Asian and Western': 'International, Asian and Western',
    'Balkan, Traditional Cuisine': 'Balkan, Traditional Cuisine',
    'Balkan, International': 'Balkan, International',
    'European, International': 'European, International',
    'International, Balkan': 'International, Balkan',
    'Southern Thai, Contemporary': 'Southern Thai, Contemporary',
    'Mediterranean Cuisine, Lebanese': 'Mediterranean Cuisine, Lebanese',
    'Meats and Grills, Steakhouse': 'Meats and Grills, Steakhouse',
    'Argentinian, Meats and Grills': 'Argentinian, Meats and Grills',
    'Steakhouse, Meats and Grills': 'Steakhouse, Meats and Grills',
    'Yakitori, French': 'Yakitori, French',
    'Nepali': 'Nepali',
    'Rice Dishes, Seafood': 'Rice Dishes, Seafood',
    'Fusion, Traditional Cuisine': 'Fusion, Traditional Cuisine',
    'Meats and Grills, Regional Cuisine': 'Meats and Grills, Regional Cuisine',
    'Farm to table, Seafood': 'Farm to table, Seafood',
    'Catalan, Seasonal Cuisine': 'Catalan, Seasonal Cuisine',
    'Asturian': 'Asturian',
    'Creative, Spanish': 'Creative, Spanish',
    'Traditional Cuisine, Rice Dishes': 'Traditional Cuisine, Rice Dishes',
    'Seafood, Galician': 'Seafood, Galician',
    'Seafood, Catalan': 'Seafood, Catalan',
    'Grills, Seafood': 'Grills, Seafood',
    'Meats and Grills, Regional European': 'Meats and Grills, Regional European',
    'Contemporary, Catalan': 'Contemporary, Catalan',
    'Regional Cuisine, Asian Influences': 'Regional Cuisine, Asian Influences',
    'Galician, Regional Cuisine': 'Galician, Regional Cuisine',
    'Catalan, Grills': 'Catalan, Grills',
    'Regional Cuisine, Rice Dishes': 'Regional Cuisine, Rice Dishes',
    'Andalusian, Farm to table': 'Andalusian, Farm to table',
    'Italian Contemporary, Seafood': 'Italian Contemporary, Seafood',
    'Traditional Cuisine, Innovative': 'Traditional Cuisine, Innovative',
    'Fusion, Peruvian': 'Fusion, Peruvian',
    'Castilian': 'Castilian',
    'Galician, Traditional Cuisine': 'Galician, Traditional Cuisine',
    'Farm to table, Meats and Seafood': 'Farm to table, Meats and Seafood',
    'Lamb Specialities, Regional European': 'Lamb Specialities, Regional European',
    'Basque, Contemporary': 'Basque, Contemporary',
    'Traditional Cuisine, Spanish': 'Traditional Cuisine, Spanish',
    'Fusion, Farm to table': 'Fusion, Farm to table',
    'Contemporary, Basque': 'Contemporary, Basque',
    'Traditional Cuisine, Catalan': 'Traditional Cuisine, Catalan',
    'Farm to table, Andalusian': 'Farm to table, Andalusian',
    'Spanish, Fusion': 'Spanish, Fusion',
    'Japanese Steakhouse': 'Japanese Steakhouse',
    'Asian Contemporary, Peruvian': 'Asian Contemporary, Peruvian',
    'Meats and Seafood, Grills': 'Meats and Seafood, Grills',
    'Traditional Cuisine, Argentinian': 'Traditional Cuisine, Argentinian',
    'Seasonal Cuisine, Innovative': 'Seasonal Cuisine, Innovative',
    'Thai, Burmese': 'Thai, Burmese',
    'Hui Cuisine': 'Hui Cuisine',
    'Chinese Contemporary, Cantonese': 'Chinese Contemporary, Cantonese',
    'Shanghainese, Huaiyang': 'Shanghainese, Huaiyang',
    'Italian Contemporary, Seasonal Cuisine': 'Italian Contemporary, Seasonal Cuisine',
    'Regional Cuisine, Italian Contemporary': 'Regional Cuisine, Italian Contemporary',
    'Italian Contemporary, Vegetarian': 'Italian Contemporary, Vegetarian',
    'Meats and Grills, Umbrian': 'Meats and Grills, Umbrian',
    'Tuscan, Contemporary': 'Tuscan, Contemporary',
    'Alpine, Mediterranean Cuisine': 'Alpine, Mediterranean Cuisine',
    'Seafood, Apulian': 'Seafood, Apulian',
    'Alpine, Traditional Cuisine': 'Alpine, Traditional Cuisine',
    'Cuisine from the Aosta Valley, Classic Cuisine': 'Cuisine from the Aosta Valley, Classic Cuisine',
    'Venetian': 'Venetian',
    'Country cooking, Creative': 'Country cooking, Creative',
    'Tuscan, Modern Cuisine': 'Tuscan, Modern Cuisine',
    'Venetian, Country cooking': 'Venetian, Country cooking',
    'Seafood, Friulian': 'Seafood, Friulian',
    'Mediterranean Cuisine, Italian Contemporary': 'Mediterranean Cuisine, Italian Contemporary',
    'Pizza, Sharing': 'Pizza, Sharing',
    'Italian Contemporary, Piedmontese': 'Italian Contemporary, Piedmontese',
    'Alpine, Contemporary': 'Alpine, Contemporary',
    'Cuisine from the Aosta Valley': 'Cuisine from the Aosta Valley',
    'Contemporary, Sicilian': 'Contemporary, Sicilian',
    'Seafood, Italian Contemporary': 'Seafood, Italian Contemporary',
    'Italian Contemporary, Country cooking': 'Italian Contemporary, Country cooking',
    'Fusion, Regional Cuisine': 'Fusion, Regional Cuisine',
    'Venetian, Seafood': 'Venetian, Seafood',
    'Italian, Venetian': 'Italian, Venetian',
    'Classic Cuisine, Tuscan': 'Classic Cuisine, Tuscan',
    'Ligurian, Classic Cuisine': 'Ligurian, Classic Cuisine',
    'Lombardian, Modern Cuisine': 'Lombardian, Modern Cuisine',
    'Cuisine from Romagna, Regional Cuisine': 'Cuisine from Romagna, Regional Cuisine',
    'Cuisine from Abruzzo, Seasonal Cuisine': 'Cuisine from Abruzzo, Seasonal Cuisine',
    'Cuisine from Basilicata, Modern Cuisine': 'Cuisine from Basilicata, Modern Cuisine',
    'Piedmontese, Contemporary': 'Piedmontese, Contemporary',
    'Country cooking, Italian Contemporary': 'Country cooking, Italian Contemporary',
    'Peruvian, Asian Influences': 'Peruvian, Asian Influences',
    'Seafood, Cuisine from Romagna': 'Seafood, Cuisine from Romagna',
    'Ligurian, Italian': 'Ligurian, Italian',
    'Ligurian, Creative': 'Ligurian, Creative',
    'Country cooking, Alpine': 'Country cooking, Alpine',
    'Modern Cuisine, South Tyrolean': 'Modern Cuisine, South Tyrolean',
    'Modern Cuisine, Piedmontese': 'Modern Cuisine, Piedmontese',
    'Tuscan, Classic Cuisine': 'Tuscan, Classic Cuisine',
    'Campanian, Contemporary': 'Campanian, Contemporary',
    'Cuisine from the Aosta Valley, Modern Cuisine': 'Cuisine from the Aosta Valley, Modern Cuisine',
    'Ligurian, Seafood': 'Ligurian, Seafood',
    'Seafood, Italian': 'Seafood, Italian',
    'Italian Contemporary, Ligurian': 'Italian Contemporary, Ligurian',
    'Tuscan, Grills': 'Tuscan, Grills',
    'Cuisine from Romagna, Seasonal Cuisine': 'Cuisine from Romagna, Seasonal Cuisine',
    'Italian, Country cooking': 'Italian, Country cooking',
    'Cuisine from Lazio': 'Cuisine from Lazio',
    'Modern Cuisine, Ligurian': 'Modern Cuisine, Ligurian',
    'Cuisine from Lazio, Home Cooking': 'Cuisine from Lazio, Home Cooking',
    'Modern Cuisine, Cuisine from Abruzzo': 'Modern Cuisine, Cuisine from Abruzzo',
    'Emilian, Regional Cuisine': 'Emilian, Regional Cuisine',
    'Japanese, Classic Cuisine': 'Japanese, Classic Cuisine',
    'Mantuan, Country cooking': 'Mantuan, Country cooking',
    'Indonesian, Fusion': 'Indonesian, Fusion',
    'Contemporary, Apulian': 'Contemporary, Apulian',
    'Ligurian, Contemporary': 'Ligurian, Contemporary',
    'Contemporary, Alpine': 'Contemporary, Alpine',
    'Sardinian, Modern Cuisine': 'Sardinian, Modern Cuisine',
    'Roman, Italian': 'Roman, Italian',
    'Cuisine from Basilicata, Country cooking': 'Cuisine from Basilicata, Country cooking',
    'Ligurian, Modern Cuisine': 'Ligurian, Modern Cuisine',
    'Fusion, Asian Contemporary': 'Fusion, Asian Contemporary',
    'Cuisine from the Marches, Creative': 'Cuisine from the Marches, Creative',
    'Cuisine from the Aosta Valley, Creative': 'Cuisine from the Aosta Valley, Creative',
    'Calabrian, Contemporary': 'Calabrian, Contemporary',
    'Campanian, Classic Cuisine': 'Campanian, Classic Cuisine',
    'Contemporary, Campanian': 'Contemporary, Campanian',
    'Fusion, Japanese Contemporary': 'Fusion, Japanese Contemporary',
    'Cantonese, Contemporary': 'Cantonese, Contemporary',
    'Classic Cuisine, Cuisine from Romagna': 'Classic Cuisine, Cuisine from Romagna',
    'Sicilian, Contemporary': 'Sicilian, Contemporary',
    'Japanese, Asian Contemporary': 'Japanese, Asian Contemporary',
    'Tuscan, Regional Cuisine': 'Tuscan, Regional Cuisine',
    'South American, Grills': 'South American, Grills',
    'Cuisine from Lazio, Classic Cuisine': 'Cuisine from Lazio, Classic Cuisine',
    'Emilian, Contemporary': 'Emilian, Contemporary',
    'Italian Contemporary, Asian Influences': 'Italian Contemporary, Asian Influences',
    'Alpine, Seasonal Cuisine': 'Alpine, Seasonal Cuisine',
    'Cuisine from the Marches, Italian Contemporary': 'Cuisine from the Marches, Italian Contemporary',
    'Lombardian, Italian': 'Lombardian, Italian',
    'Contemporary, Lombardian': 'Contemporary, Lombardian',
    'Regional Cuisine, South Tyrolean': 'Regional Cuisine, South Tyrolean',
    'International, Small eats': 'International, Small eats',
    'Mediterranean Cuisine, Sicilian': 'Mediterranean Cuisine, Sicilian',
    'Grills, Regional Cuisine': 'Grills, Regional Cuisine',
    'Cuisine from Valtellina, Lombardian': 'Cuisine from Valtellina, Lombardian',
    'Italian Contemporary, Contemporary': 'Italian Contemporary, Contemporary',
    'Roman, Farm to table': 'Roman, Farm to table',
    'Umbrian, Modern Cuisine': 'Umbrian, Modern Cuisine',
    'Mantuan, Classic Cuisine': 'Mantuan, Classic Cuisine',
    'Farm to table, Italian Contemporary': 'Farm to table, Italian Contemporary',
    'Modern Cuisine, Campanian': 'Modern Cuisine, Campanian',
    'Calabrian, Classic Cuisine': 'Calabrian, Classic Cuisine',
    'Classic Cuisine, Grills': 'Classic Cuisine, Grills',
    'Cuisine from Abruzzo, Classic Cuisine': 'Cuisine from Abruzzo, Classic Cuisine',
    'Sicilian, Creative': 'Sicilian, Creative',
    'Sardinian, Home Cooking': 'Sardinian, Home Cooking',
    'Traditional Cuisine, Mantuan': 'Traditional Cuisine, Mantuan',
    'Cuisine from the Marches, Italian': 'Cuisine from the Marches, Italian',
    'Campanian, Seafood': 'Campanian, Seafood',
    'Tuscan, Italian Contemporary': 'Tuscan, Italian Contemporary',
    'Classic Cuisine, Alpine': 'Classic Cuisine, Alpine',
    'Roman, Classic Cuisine': 'Roman, Classic Cuisine',
    'Cuisine from the Aosta Valley, Traditional Cuisine': 'Cuisine from the Aosta Valley, Traditional Cuisine',
    'Innovative, Umbrian': 'Innovative, Umbrian',
    'Italian Contemporary, Lombardian': 'Italian Contemporary, Lombardian',
    'Tuscan, Creative': 'Tuscan, Creative',
    'Meats and Grills, Contemporary': 'Meats and Grills, Contemporary',
    'Italian, Meats and Grills': 'Italian, Meats and Grills',
    'Umbrian, Contemporary': 'Umbrian, Contemporary',
    'Asian Contemporary, Tuscan': 'Asian Contemporary, Tuscan',
    'Seafood, Sicilian': 'Seafood, Sicilian',
    'Milanese, Lombardian': 'Milanese, Lombardian',
    'Italian Contemporary, Cuisine from the Aosta Valley': 'Italian Contemporary, Cuisine from the Aosta Valley',
    'Roman, Mediterranean Cuisine': 'Roman, Mediterranean Cuisine',
    'Piedmontese, Italian Contemporary': 'Piedmontese, Italian Contemporary',
    'Cuisine from Romagna, Modern Cuisine': 'Cuisine from Romagna, Modern Cuisine',
    'Italian Contemporary, Venetian': 'Italian Contemporary, Venetian',
    'Meats and Grills, Mediterranean Cuisine': 'Meats and Grills, Mediterranean Cuisine',
    'Piedmontese, Italian': 'Piedmontese, Italian',
    'Italian Contemporary, Vegan': 'Italian Contemporary, Vegan',
    'Tuscan, Seasonal Cuisine': 'Tuscan, Seasonal Cuisine',
    'Traditional Cuisine, Piedmontese': 'Traditional Cuisine, Piedmontese',
    'Mantuan, Italian Contemporary': 'Mantuan, Italian Contemporary',
    'Seafood, Sardinian': 'Seafood, Sardinian',
    'Contemporary, Ligurian': 'Contemporary, Ligurian',
    'Cuisine from Basilicata, Italian': 'Cuisine from Basilicata, Italian',
    'Piedmontese, Mediterranean Cuisine': 'Piedmontese, Mediterranean Cuisine',
    'Cuisine from the Marches, Country cooking': 'Cuisine from the Marches, Country cooking',
    'Contemporary, Asian Influences': 'Contemporary, Asian Influences',
    'Calabrian, Modern Cuisine': 'Calabrian, Modern Cuisine',
    'Meats and Grills, Italian': 'Meats and Grills, Italian',
    'Cuisine from Abruzzo, Modern Cuisine': 'Cuisine from Abruzzo, Modern Cuisine',
    'Campanian, Creative': 'Campanian, Creative',
    'Cuisine from Valtellina, Modern Cuisine': 'Cuisine from Valtellina, Modern Cuisine',
    'Mediterranean Cuisine, Ligurian': 'Mediterranean Cuisine, Ligurian',
    'Italian Contemporary, Emilian': 'Italian Contemporary, Emilian',
    'Italian Contemporary, Grills': 'Italian Contemporary, Grills',
    'Piedmontese, Farm to table': 'Piedmontese, Farm to table',
    'Steakhouse, Italian Contemporary': 'Steakhouse, Italian Contemporary',
    'Contemporary, Tuscan': 'Contemporary, Tuscan',
    'Contemporary, Grills': 'Contemporary, Grills',
    'Italian Contemporary, Sicilian': 'Italian Contemporary, Sicilian',
    'Peruvian, Japanese': 'Peruvian, Japanese',
    'Russian, Turkish': 'Russian, Turkish',
    'Turkish, Country cooking': 'Turkish, Country cooking',
    'Asian Influences, Turkish': 'Asian Influences, Turkish',
    'Meats and Grills, Turkish': 'Meats and Grills, Turkish',
    'Asian and Western, World Cuisine': 'Asian and Western, World Cuisine',
    'Cantonese, Modern Cuisine': 'Cantonese, Modern Cuisine',
    'Traditional Cuisine, Turkish': 'Traditional Cuisine, Turkish',
    'Vietnamese, Asian': 'Vietnamese, Asian',
    'Asian, Dim Sum': 'Asian, Dim Sum',
    'French, Alsatian': 'French, Alsatian',
    'Asian, Ramen': 'Asian, Ramen',
    'Latin American, Contemporary': 'Latin American, Contemporary',
    'Contemporary, Caribbean': 'Contemporary, Caribbean',
    'Japanese, Steakhouse': 'Japanese, Steakhouse',
    'Ethiopian, Regional Cuisine': 'Ethiopian, Regional Cuisine',
    'International, American': 'International, American',
    'Latin American, Mexican': 'Latin American, Mexican',
    'Caribbean': 'Caribbean',
    'Sushi, Japanese Contemporary': 'Sushi, Japanese Contemporary',
    'Cantonese, American': 'Cantonese, American',
    'English, Contemporary': 'English, Contemporary',
    'Middle Eastern, Regional Cuisine': 'Middle Eastern, Regional Cuisine',
    'Contemporary, Innovative': 'Contemporary, Innovative',
    'Latin American, Regional Cuisine': 'Latin American, Regional Cuisine',
    'Persian, Regional Cuisine': 'Persian, Regional Cuisine',
    'Puerto Rican, Pork': 'Puerto Rican, Pork',
    'Mediterranean Cuisine, Gastropub': 'Mediterranean Cuisine, Gastropub',
    'Steakhouse, Italian': 'Steakhouse, Italian',
    'South East Asian, Seafood': 'South East Asian, Seafood',
    'American, Grills': 'American, Grills',
    'Japanese, French Contemporary': 'Japanese, French Contemporary',
    'Fusion, American': 'Fusion, American',
    'Korean Contemporary, Asian': 'Korean Contemporary, Asian',
    'European Contemporary, French': 'European Contemporary, French',
    'Indonesian, South East Asian': 'Indonesian, South East Asian',
    'Japanese, Shabu-shabu': 'Japanese, Shabu-shabu',
    'Chinese, Hunanese': 'Chinese, Hunanese',
    'Cantonese, Asian': 'Cantonese, Asian',
    'Spanish, Seafood': 'Spanish, Seafood',
    'Italian, Sardinian': 'Italian, Sardinian',
    'Austrian, Contemporary': 'Austrian, Contemporary',
    'Jamaican': 'Jamaican',
    'Vegan, Southern': 'Vegan, Southern',
    'Italian, Piedmontese': 'Italian, Piedmontese',
    'Italian, French': 'Italian, French',
    'American Contemporary, Regional Cuisine': 'American Contemporary, Regional Cuisine',
    'Taiwanese, Asian': 'Taiwanese, Asian',
    'Contemporary, European': 'Contemporary, European',
    'Venezuelan, Latin American': 'Venezuelan, Latin American',
    'Contemporary, Italian-American': 'Contemporary, Italian-American',
    'Contemporary, South East Asian': 'Contemporary, South East Asian',
    'Balkan, Country cooking': 'Balkan, Country cooking',
    'Contemporary, Eastern European': 'Contemporary, Eastern European',
    'Chinese, Hotpot': 'Chinese, Hotpot',
    'Japanese, Asian Influences': 'Japanese, Asian Influences',
    'Gastropub, American': 'Gastropub, American',
    'Pizza, American': 'Pizza, American',
    'Japanese, Okonomiyaki': 'Japanese, Okonomiyaki',
    'Fusion, Creole': 'Fusion, Creole',
    'Chinese, Chinese Contemporary': 'Chinese, Chinese Contemporary',
    'Croatian, Italian': 'Croatian, Italian',
    'Italian-American, Regional Cuisine': 'Italian-American, Regional Cuisine',
    'South East Asian, Indian': 'South East Asian, Indian',
    'Seafood, Latin American': 'Seafood, Latin American',
    'Southern, Cajun': 'Southern, Cajun',
    'Indonesian, Balinese': 'Indonesian, Balinese',
    'Lao, Street Food': 'Lao, Street Food',
    'Contemporary, Shellfish Specialities': 'Contemporary, Shellfish Specialities',
    'Japanese Contemporary, Sushi': 'Japanese Contemporary, Sushi',
    'Hawaiian, Contemporary': 'Hawaiian, Contemporary',
    'Moroccan, Regional Cuisine': 'Moroccan, Regional Cuisine',
    'Steakhouse, Seafood': 'Steakhouse, Seafood',
    'African, Contemporary': 'African, Contemporary',
    'Cantonese, Seafood': 'Cantonese, Seafood',
    'Vegan, North American': 'Vegan, North American',
    'Vietnamese, Vegetarian': 'Vietnamese, Vegetarian',
    'Italian, North American': 'Italian, North American',
    'North American, Regional Cuisine': 'North American, Regional Cuisine',
    'Spanish, Small eats': 'Spanish, Small eats',
    'Chinese, Shaanxi': 'Chinese, Shaanxi',
    'Steakhouse, North American': 'Steakhouse, North American',
    'Peruvian, Regional Cuisine': 'Peruvian, Regional Cuisine',
    'Seafood, North American': 'Seafood, North American',
    'Italian, Spanish Contemporary': 'Italian, Spanish Contemporary',
    'World Cuisine, Fusion': 'World Cuisine, Fusion',
    'French Contemporary, Sharing': 'French Contemporary, Sharing',
    'Austrian, Classic Cuisine': 'Austrian, Classic Cuisine',
    'Swiss, International': 'Swiss, International',
    'Mediterranean Cuisine, Classic French': 'Mediterranean Cuisine, Classic French',
    'Mediterranean Cuisine, Swiss': 'Mediterranean Cuisine, Swiss',
    'Traditional Cuisine, Asian': 'Traditional Cuisine, Asian',
    'Modern Cuisine, Vegetarian': 'Modern Cuisine, Vegetarian',
    'Fusion, International': 'Fusion, International',
    'Peruvian, Japanese Contemporary': 'Peruvian, Japanese Contemporary',
    'Swiss, Mediterranean Cuisine': 'Swiss, Mediterranean Cuisine',
    'Regional Cuisine, Swiss': 'Regional Cuisine, Swiss',
    'Traditional Cuisine, Alpine': 'Traditional Cuisine, Alpine',
    'Vegetarian, Seasonal Cuisine': 'Vegetarian, Seasonal Cuisine',
    'Swiss, Cheese, Fondue and Raclette': 'Swiss, Cheese, Fondue and Raclette',
    'Innovative, Swiss': 'Innovative, Swiss',
    'American, Asian': 'American, Asian',
    'Thai, Southern Thai': 'Thai, Southern Thai',
    'Egyptian, Regional Cuisine': 'Egyptian, Regional Cuisine',
    'French, Steakhouse': 'French, Steakhouse',
    'Italian, Vegetarian': 'Italian, Vegetarian',
    'Peruvian, World Cuisine': 'Peruvian, World Cuisine',
    'Mediterranean Cuisine, Hungarian': 'Mediterranean Cuisine, Hungarian',
    'International, South American': 'International, South American',
    'Russian': 'Russian',
    'American, Mexican': 'American, Mexican',
    'South African, Modern Cuisine': 'South African, Modern Cuisine',
    'World Cuisine, Creative French': 'World Cuisine, Creative French',
    'Asian Influences, World Cuisine': 'Asian Influences, World Cuisine',
    'Savoyard, Creative': 'Savoyard, Creative',
    'Portuguese, Asian Influences': 'Portuguese, Asian Influences',
    'South American, Asian': 'South American, Asian',
    'Creative, Scandinavian': 'Creative, Scandinavian',
    'Modern Cuisine, Greek': 'Modern Cuisine, Greek',
    'Chinese, Indonesian': 'Chinese, Indonesian',
    'World Cuisine, Modern French': 'World Cuisine, Modern French',
    'Meats and Grills, Creative': 'Meats and Grills, Creative',
    'Modern Cuisine, Cuisine from the Marches': 'Modern Cuisine, Cuisine from the Marches',
    'French, Fusion': 'French, Fusion',
    'Modern French, Vegetarian': 'Modern French, Vegetarian',
    'Modern British, International': 'Modern British, International',
    'Modern French, Home Cooking': 'Modern French, Home Cooking',
    'Modern French, Classic French': 'Modern French, Classic French',
    'Scandinavian, Country cooking': 'Scandinavian, Country cooking',
    'Modern Cuisine, Austrian': 'Modern Cuisine, Austrian',
    'Czech, Contemporary': 'Czech, Contemporary'}